- docs/_coverpage.md
- docs/analysis/metrics.md
- docs/contributing/build-instructions.md
- docs/contributing/chrome-branches.md
- docs/contributing/getting-started.md
- docs/contributing/sdk-releasing.md
- docs/contributing/testing.md
- docs/contributing/ui-plugins.md
- docs/design-docs/continuous-integration.md
- docs/instrumentation/heapprofd-api.md
- docs/instrumentation/tracing-sdk.md
- docs/quickstart/linux-tracing.md
> update docs AOSP -> GitHub

- tools/test_data
We seem to be hitting some network failures on the CI. Add retries.
> tools: add retries to test_data

- src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrace.java
- src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrackEventExtra.java
- src/android_sdk/java/test/dev/perfetto/sdk/test/PerfettoTraceTest.java
Use 'google-java-format' with default settings.
> Format Android SDK '.java' code and test files.

- .github/CODEOWNERS
This will allow us to add protections on who can approve PRs.
> github: setup codeowners

- .github/workflows/protect-branches.yml
This prevents stacked PRs from being accidentally merged
> github: only allow PRs onto main/ui-canary/ui-stable

- src/trace_processor/importers/ftrace/ftrace_parser.cc
- src/trace_processor/importers/ftrace/ftrace_tokenizer.cc
- Comment out parsing param_set_value_cpm events in ftrace_parser
- Comment out tokenizing param_set_value_cpm events in ftrace_tokenizer
Bug: 407000648
Test: run ui/run-dev-server
> thermal: perfetto/ftrace: Disable parsing param_set_value_cpm

- ui/src/frontend/viewer_page/current_selection_tab.ts
- ui/src/frontend/viewer_page/notes_panel.ts
- ui/src/plugins/dev.perfetto.AndroidCujs/index.ts
- ui/src/plugins/dev.perfetto.Io/index.ts
- ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinBlockingCall.ts
- ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinBlockingCall_unittest.ts
- ui/src/plugins/dev.perfetto.ThreadState/thread_state_details_panel.ts
- ui/src/test/queries.test.ts
- ui/src/widgets/split_panel.ts
Run `ui/format-sources --all`.
> Run auto formatter on UI codebase

- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.cc
- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.h
No behavioural change, just making the code more linear and easy to follow.
> tp: refactor engine to prepare for dataframe integration in create perfetto table

- tools/git_new_branch.py
- tools/git_prune_all.py
* Make prune_all consider origin/main to delete top level empty branches
* Make new_branch less chatty and use origin/main if not on branch
> git: small fixes to scripts

- src/base/android_utils.cc
> Guard include statements with same build flags as code in android_utils

- infra/luci/recipes/perfetto.expected/ci_win.json
- infra/luci/recipes/perfetto.py
This reverts commit 0ea38dfcc30c4f124a3d7c7c564187beee58319b.
It doesn't fix the problem, it actually makes it worse.
> Revert "luci: Use python.exe instead of python3.exe on windows (#1251)"

- ui/src/assets/perfetto.scss
- ui/src/assets/widgets/multiselect_input.scss
- ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
- ui/src/widgets/multiselect_input.ts
- ui/src/widgets/popup.ts
Add a new multiselect widget that allows selecting multiple items from a dropdown by typing in a text input.
> Add MultiselectInput widget

- Android.bp
- BUILD
- src/trace_processor/metrics/sql/chrome/BUILD.gn
- test/trace_processor/diff_tests/include_index.py
- test/trace_processor/diff_tests/metrics/chrome/tests_scroll_jank.py
It was removed in https://r.android.com/3486413 but some clients still need it.
Bug: #1303
> Re-add chrome_scroll_jank_v3 metric

- CHANGELOG
> docs: Add CHANGELOG for v50

- include/perfetto/ext/base/http/http_server.h
- include/perfetto/ext/base/unix_socket.h
- src/base/http/http_server.cc
- src/base/unix_socket.cc
- src/trace_processor/rpc/httpd.cc
- src/trace_processor/rpc/httpd.h
- src/trace_processor/trace_processor_shell.cc
Multiple reasons:
1) It's breaking on Windows
2) It's failing in Borg
This reverts commit 2184503eb9cfe863bc5e0191e94b95368a5ab945.
> Revert "tp: support listening on specified ip (#1259)"

- gn/proto_library.gni
This is necessary for https://crrev.com/c/6442961
> Update proto_library template to propagate indirect input deps correctly.

- protos/perfetto/common/system_info.proto
- protos/perfetto/trace/ftrace/ftrace_event_bundle.proto
- protos/perfetto/trace/perfetto_trace.proto
Clarify stale comment and fix up a "next id".
> protos: comment fixups

- include/perfetto/ext/base/http/http_server.h
- include/perfetto/ext/base/unix_socket.h
- src/base/http/http_server.cc
- src/base/http/http_server_unittest.cc
- src/base/unix_socket.cc
- src/trace_processor/rpc/httpd.cc
- src/trace_processor/rpc/httpd.h
- src/trace_processor/trace_processor_shell.cc
- src/websocket_bridge/websocket_bridge.cc
Reland of https://github.com/google/perfetto/pull/1259 but with fixes for build on Windows and binding behaviour on poorly configured machines.
> [reland] tp: support listening on specified ip

- protos/perfetto/trace/android/surfaceflinger_layers.proto
- protos/perfetto/trace/android/surfaceflinger_transactions.proto
- protos/perfetto/trace/perfetto_trace.proto
- test/trace_processor/diff_tests/syntax/table_tests.py
Test: atest LayerLifecycleManagerTest
Bug: 391463550
Flag: com.android.systemui.spatial_model_pushback_in_shader
Change-Id: I97f784cbfcb635a3576116edb274fdc22a499495
> Add background_blur_scale to SF layer/transaction

- protos/perfetto/trace/android/server/windowmanagerservice.proto
Bug: N/A
Test: N/A
Flag: EXEMPT mechanical
Change-Id: I40bfd026fd7d4eeaaf82069fa8d39939ea47cd30
> Deprecate unused APP_STATE_TIMEOUT

- docs/contributing/ui-plugins.md
`trace.registerDetailsPanel()` no longer exists and the docs are out of date
> Remove out-of-date docs

- src/kernel_utils/BUILD.gn
- src/trace_processor/importers/etw/etw_parser.cc
- src/traced/probes/android_kernel_wakelocks/BUILD.gn
- tools/gen_tp_table_headers.py
Run `tools/format-sources --all`
> Run formatter

- src/trace_processor/perfetto_sql/engine/dataframe_module.cc
- src/trace_processor/perfetto_sql/engine/dataframe_module.h
- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.cc
- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.h
- src/trace_processor/perfetto_sql/engine/runtime_table_function.cc
- src/trace_processor/perfetto_sql/engine/runtime_table_function.h
- src/trace_processor/perfetto_sql/intrinsics/operators/counter_mipmap_operator.cc
- src/trace_processor/perfetto_sql/intrinsics/operators/counter_mipmap_operator.h
- src/trace_processor/perfetto_sql/intrinsics/operators/slice_mipmap_operator.cc
- src/trace_processor/perfetto_sql/intrinsics/operators/slice_mipmap_operator.h
- src/trace_processor/perfetto_sql/intrinsics/table_functions/table_info.cc
- src/trace_processor/perfetto_sql/intrinsics/table_functions/winscope_proto_to_args_with_defaults.cc
- src/trace_processor/sqlite/bindings/sqlite_module.h
- src/trace_processor/sqlite/db_sqlite_table.cc
- src/trace_processor/sqlite/db_sqlite_table.h
- src/trace_processor/sqlite/module_state_manager.cc
- src/trace_processor/sqlite/module_state_manager.h
We tried several partial solutions to the problem, I believe this should now
be the final word on the topic.
> tp: resolve nested transactions once and for all

- ui/src/plugins/dev.perfetto.AndroidLongBatteryTracing/index.ts
And therefore enable long battery plugin for all traces again.
Bug: http://b/409823908
> Move device state tracks into a group.

- ui/src/plugins/dev.perfetto.ExplorePage/OWNERS
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_canvas.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/styles.scss
Move styles into styles.scss, added warning if the node is invalid
> Explore Page: styles fixes

- src/protovm/slab_allocator.h
> protovm: fix chromium build

- protos/perfetto/config/ftrace/frozen_ftrace_config.proto
- protos/perfetto/config/perfetto_config.proto
- protos/perfetto/trace/perfetto_trace.proto
Change the accidentally introduced "required" proto field.
They're a historical mistake: https://protobuf.dev/best-practices/dos-donts/#add-required.
> protos: s/required/optional/

- tools/git_new_branch.py
- tools/run_presubmit
* new-branch no longer sets upstream, uses origin/main by default
* presubmit always runs against origin/main
> perfetto: improve scripts

- ui/src/plugins/dev.perfetto.AndroidLog/logs_panel.ts
Display the log PID/TID in the android logs tab to match the output of "adb logcat"
This data is already being queried so the main cost is the small amount of screen real estate.
> ui: display pid/tid in android logs view to match "adb logcat"

- src/trace_processor/perfetto_sql/preprocessor/perfetto_sql_preprocessor.cc
> tp: fix apply call in a macro

- .github/workflows/repo-checks.yml
- tools/run_presubmit
check_sql_* is already part of run_presubmits
hence there is no need to re-run it individually.
Bug: 417658300
> ci: run presubmits in Github Actions

- test/trace_processor/diff_tests/stdlib/android/android_kernel_wakelocks.textproto
- test/trace_processor/diff_tests/stdlib/android/tests.py
Add a difftest for android_kernel_wakelocks.
> Add a difftest for android_kernel_wakelocks.

- Android.bp
- BUILD
- src/trace_processor/importers/proto/BUILD.gn
- src/trace_processor/importers/proto/additional_modules.cc
- src/trace_processor/importers/proto/deobfuscation_module.cc
- src/trace_processor/importers/proto/deobfuscation_module.h
- src/trace_processor/importers/proto/heap_graph_module.cc
- src/trace_processor/importers/proto/heap_graph_module.h
- src/trace_processor/importers/proto/profile_module.cc
No functional change.
Bug: https://b.corp.google.com/issues/153632336
> tp: Move heap_graph deobfuscation into a separate module

- protos/perfetto/trace/android/server/windowmanagerservice.proto
Port of internal commit.
**Original commit message:**
Subject: Introduce proto to test Activity#requestOpenInBrowserEducation API
This CL is a port of ag/31516935 into external/perfetto.
Bug: 376903053
Test: atest CtsWindowManagerDeviceActivity:OpenInBrowserTests
Flag: EXEMPT adding cts tests
Change-Id: I510f248ebbd8f21d0d1e7a6f3000c4974cfa9569
---
Original internal commit hash: 3aecc22684441921fdf124e392b920ae227c1205
Cherry-picked with `-x`.
This PR is part of a stack. Base branch: dev/d95cff731a
> WIP: Port: Introduce proto to test Activity#requestOpenInBrowserEducation API

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_data_viewer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/styles.scss
Decoupled table from query node explorer and added layout control
> ui: ep: Control table layout

- ui/src/components/tracks/base_slice_track.ts
Fixes: https://b.corp.google.com/issues/420635799
> Fix crash when track is empty

- docs/deployment/deploying-bigtrace-on-kubernetes.md
Update several script locations in the guide that have changed over time to perform GKE deployments and add some GCP commands that were required but not documented.
> Update Bigtrace GKE guide with updated paths for deployments

- Android.bp
- BUILD
- src/trace_processor/dataframe/dataframe.h
- src/trace_processor/dataframe/runtime_dataframe_builder.h
- src/trace_processor/dataframe/runtime_dataframe_builder_unittest.cc
- src/trace_processor/perfetto_sql/engine/dataframe_module.cc
- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.cc
- src/trace_processor/perfetto_sql/intrinsics/table_functions/BUILD.gn
- src/trace_processor/perfetto_sql/intrinsics/table_functions/dataframe_query_plan_decoder.cc
- src/trace_processor/perfetto_sql/intrinsics/table_functions/dataframe_query_plan_decoder.h
- src/trace_processor/perfetto_sql/intrinsics/table_functions/tables.py
- src/trace_processor/trace_processor_impl.cc
Also other small misc fixes around dataframe
> tp: add table function for debugging dataframe query plans

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/slices_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/sql_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/stdlib_table.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
Preamble is not needed anywhere anymore, so remove it from SQL source
> ui: Explore Page: Don't require preamble in SQL source nodes

- tools/run_presubmit
Otherwise we get complaints on CI that origin/main does not exist
> presubmit: propogate merge base to formatting script

- .github/workflows/chromium-copybara-import.yml
This CL modifies the workflow to explicitly set the message of the scheduled merge commit.
> Fix Chromium Copybara workflow (round two)

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_data_viewer.ts
Show table (default in the bottom right side) also when there are no results - do it to keep the layout consistent and fix the bug with SQL source
> ui: Explore Page: Always visualise table

- src/trace_processor/tables/BUILD.gn
Fixes: https://github.com/google/perfetto/issues/1813
> tp: remove dead build rule

- src/traced/probes/ftrace/ftrace_config_muxer.cc
This reverts commit 6f29d82dce0568ade817f98f20bf781d5e8579e0.
> Revert "probes: don't assume boot clock when preserve_ftrace_buffer is set (#1722)"

- src/trace_processor/importers/json/json_trace_tokenizer.cc
- test/trace_processor/diff_tests/parser/json/tests.py
Fixes: https://github.com/google/perfetto/issues/1822
> tp: allowing trailing commans in json trace array

- src/trace_processor/tables/track_tables.py
export_json uses these columns post finalization
> tp: add missing annotation for export_json

- CHANGELOG
- python/perfetto/trace_processor/api.py
- python/perfetto/trace_processor/platform.py
- python/perfetto/trace_processor/shell.py
- python/test/api_integrationtest.py
People are using this feature using extra_flags, we might as well
support it for real.
> tp: add ability to add sql packages from Python API

- src/trace_processor/trace_processor_shell.cc
Dots are harmless if they appear in the root prefix as they will
not be part of the module key. And if they appear in the module path
then skip the module with an error message instead of failing
everything.
> tp: relax condition of path name not having dots

- src/tracing/internal/track_event_internal.cc
> Fix mac build

- docs/visualization/perfetto-ui.md
This patch adds some instructions with videos for basic UI usage, including basic timeline navigation and track manipluation.
> docs: Improve 'Trace Visualization->Perfetto UI' docs

- tools/git_sync_stack.py
* various misc style improvements
* update mainline branches to include ui-stable, ui-canary
* add --no-verify support
> tools: improve script for sync stack

- src/trace_processor/trace_processor_impl.cc
- src/trace_processor/trace_processor_impl.h
- src/trace_processor/trace_processor_shell.cc
Inspired by https://github.com/google/perfetto/pull/2020 but changed to
actually respect our API semantics.
> tp: reduce number of calls to BuildBoundsTable

- src/trace_processor/perfetto_sql/generator/structured_query_generator.cc
- src/trace_processor/perfetto_sql/generator/structured_query_generator_unittest.cc
Adds cycle detection to the structured query generator to prevent infinite loops when a query directly or indirectly references itself.
The generator now tracks the dependency chain of each query. If a query references a shared query that is already in its dependency chain, an error is returned.
This is implemented by adding a parent index to the internal query state and checking for cycles when resolving shared queries by ID.
Unit tests have been added to verify that both direct (a -> a) and indirect (a -> b -> a) cycles are detected.
> tp: Detect cycles in structured query generator

- ui/src/components/aggregation_adapter.ts
Cherry pick for https://buganizer.corp.google.com/issues/430007195
> Fix crash when making a 0 length aggregation (#1889)

- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.cc
- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.h
- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_parser.cc
- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_parser.h
- src/trace_processor/importers/proto/winscope/winscope_module.cc
> Parse SF trace into new tables.

- Android.bp
- src/trace_processor/importers/proto/BUILD.gn
- src/trace_processor/importers/proto/winscope/BUILD.gn
- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_test_utils.h
- src/trace_processor/importers/proto/winscope/surfaceflinger_layers_visibility_computation_unittest.cc
Unit test SF visibility computation.
Bug: 411363817
Test: tools/ninja -C out/linux_clang_release perfetto_unittests && out/linux_clang_release/perfetto_unittests --gtest_filter=SfVisibilityComputation*
> tp: SF visibility computation unit tests

- src/trace_processor/importers/json/json_trace_tokenizer.cc
- src/trace_processor/importers/json/json_trace_tokenizer.h
- test/trace_processor/diff_tests/parser/json/tests.py
* fix parsing of string timestamps, we were causing an infinite
recursion before
* fix parsing of global id2 values, we were comparing the wrong
key before and also not correctly passing the id2 by ref
Add tests for all of this + some more things I spotted along the way.
Fixes: https://github.com/google/perfetto/issues/2067
> tp: multiple small fixes for JSON trace tokenization

- src/trace_processor/importers/json/json_trace_parser_impl.cc
- src/trace_processor/importers/json/json_trace_tokenizer.cc
Fixes: https://github.com/google/perfetto/issues/2048
> tp: fix thread name association (#2058)

- ui/src/components/aggregation_adapter.ts
Cherry pick #2082 to stable - Optimize union dataset in aggregations
> ui: Cherry pick optimize union dataset fix - stable

- ui/release/channels.json
This roll is to land the fix in #2082 on canary and stable.
> ui: Roll stable & canary

- src/tracing/internal/track_event_internal.cc
Suggested-by: gkaiser@google.com
> Use const reference in ForEachObserverForRegistries

- src/trace_processor/perfetto_sql/engine/static_table_function_module.cc
> tp: fix crash when doing star queries over static table functions

- ui/src/base/clipboard.ts
- ui/src/base/download_utils.ts
- ui/src/base/json_utils.ts
- ui/src/base/json_utils_unittest.ts
- ui/src/components/query_table/queries.ts
- ui/src/components/query_table/queries_unittest.ts
- ui/src/components/query_table/query_table.ts
- ui/src/components/widgets/data_grid/data_grid.ts
- ui/src/frontend/sidebar.ts
- ui/src/frontend/trace_converter.ts
- ui/src/plugins/dev.perfetto.RecordTraceV2/pages/target_selection_page.ts
- Merge download functions into download() and downloadUrl() and make more generic and more useful.
- Extract functions to format query results into their own file and add unit tests.
- Add `space` option to serializeJsonWithBigints() for formatted JSON.
> ui: Improve download & serialization utils

- ui/src/components/widgets/data_grid/common.ts
- ui/src/components/widgets/data_grid/data_grid.ts
- Hide sort controls when sorting is disabled.
- Allow mithril nodes to be passed as column titles.
> ui: Various DataGrid fixes

- src/trace_processor/perfetto_sql/stdlib/android/binder_breakdown.sql
Not ordering by id was killing performance.
> tp: signifcantly improve perf of binder metric

- src/trace_processor/dataframe/dataframe.cc
- src/trace_processor/dataframe/dataframe_unittest.cc
- src/trace_processor/perfetto_sql/engine/dataframe_module.cc
- src/trace_processor/perfetto_sql/engine/dataframe_module.h
- src/trace_processor/perfetto_sql/engine/perfetto_sql_engine.cc
- src/trace_processor/perfetto_sql/stdlib/prelude/after_eof/indexes.sql
Both of these are very common columns to join on so have indexes.
Considered also adding one on slice but not doing that for now.
> tp: create indexes on slice.parent_id and slice.track_id

- src/trace_processor/importers/common/slice_tracker.cc
- test/trace_processor/diff_tests/parser/parsing/tests.py
* deal with cases where instant happen at the same time as a slice
* Add some more tests around this to validate our behaviour
Fixes: b/433498885
> tp: yet another round of fixing slice stacking with identical tses

- src/trace_processor/importers/proto/proto_trace_tokenizer.h
> Fix uint overflow in proto_trace_tokenizer

- bazel/sqlite.BUILD
- buildtools/BUILD.gn
- test/trace_processor/diff_tests/stdlib/prelude/math_functions_tests.py
Also sync bazel flags with GN flags which should always be 1:1
Fixes: https://github.com/google/perfetto/issues/2280
> tp: add sqlite math functions to standalone build and bazel

- CONTRIBUTORS.txt
- docs/contributing/become-a-committer.md
- docs/toc.md
> docs: add committer instructions

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/filter.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/operation_component.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/slices_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/sql_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/sources/stdlib_table.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
To use the table filters we need to first move to use the same FilterDefinition as the DataGrid
> exp: Use FilterDefinition from DataGrid implementation

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/filter.ts
Removing properties from UIFilter that should have been stored in Operator/Editor
> exp: Small noop cleanup of FilterOperator

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/aggregations.scss
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/aggregations.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/filter.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/operation_component.scss
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/operation_component.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
Nicer and more polished Aggregations support in Explore Page
> exp: Cleanup the AggregationsOperator

- Android.bp
- BUILD
- src/trace_processor/perfetto_sql/stdlib/linux/perf/BUILD.gn
- src/trace_processor/perfetto_sql/stdlib/linux/perf/etm.sql
- test/trace_processor/diff_tests/parser/etm/tests.py
- test/trace_processor/diff_tests/parser/simpleperf/tests.py
Adds a Perfetto SQL Function that gets the file_name and rel_pc for a specific ETM trace_id.
> tp: stdlib: adds _linux_perf_etm_metadata to get file_name and rel_pc

- test/configs/android_syshealth.cfg
This is just to make it easier to recommend this config to others!
> Add the recommended Android trace config to the repo.

- src/trace_processor/importers/ftrace/pkvm_hyp_cpu_tracker.cc
- src/trace_processor/importers/ftrace/pkvm_hyp_cpu_tracker.h
Move interning of remaining keys into c-tor
> Cleanup pkvm_hyp_cpu_tracker

- src/trace_processor/tables/winscope_tables.py
- test/trace_processor/diff_tests/syntax/table_tests.py
Fixes: 436501138
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell
> Transition id column not necessarily sorted.

- src/trace_processor/sorter/trace_sorter.cc
- src/trace_processor/sorter/trace_sorter.h
We were adding to the token buffer but not inserting the event in the
case of negative timestamps. Pull the checks up to before we add to the
token buffer. Also inline them to be more efficient.
> tp: fix crash in sorter on negative timestamps

- .github/workflows/gemini-cli.yml
- .github/workflows/gemini-issue-automated-triage.yml
- .github/workflows/gemini-issue-scheduled-triage.yml
- .github/workflows/gemini-pr-review.yml
Just an trial experiment to see if it's useful. Will disable if not.
For now, is using my personal Gemini API key, we should move it to a proper key if we decide to keep this moving forward.
> github: experimental: gemini-cli GH action

- ui/src/plugins/com.google.PixelMemory/index.ts
Bug: 436836845
Test: load traces and check the plugin result.
> ui: add a cmd to show process total memory excluding rss file

- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_explorer.ts
- ui/src/plugins/dev.perfetto.RecordTraceV2/pages/instructions_page.ts
- ui/src/plugins/dev.perfetto.RecordTraceV2/styles.scss
> ui: Use CodeSnippet widget in record page & explore page

- Android.bp
- BUILD
- src/trace_processor/metrics/sql/android/java_heap_histogram.sql
- src/trace_processor/perfetto_sql/stdlib/android/memory/heap_graph/BUILD.gn
- src/trace_processor/perfetto_sql/stdlib/android/memory/heap_graph/class_relationship.sql
- src/trace_processor/perfetto_sql/stdlib/graphs/scan.sql
Reapply "tp: update android_special_classes with graph.scan and add heap_graph.class_relationship module" (#2486) with fixes: remove nulls from input tables to _graph_scan
b/427894998, b/437640299
> Reapply "tp: update android_special_classes with graph.scan and add heap_graph.class_relationship module" #2486

- ui/src/assets/sidebar.scss
- ui/src/assets/theme_provider.scss
> ui: Themed scrollbars

- src/trace_processor/importers/common/event_tracker.cc
- src/trace_processor/importers/common/event_tracker.h
- src/trace_processor/importers/ftrace/ftrace_parser.cc
- src/trace_processor/importers/ftrace/ftrace_parser.h
> ui: Add track for dmabuf_rss_stat

- docs/getting-started/other-formats.md
The instructions were full of incorrect paths and flags.
> docs: other formats: fix simpleperf -> gecko instructions

- src/profiling/symbolizer/breakpad_symbolizer.cc
- src/profiling/symbolizer/breakpad_symbolizer.h
- src/profiling/symbolizer/breakpad_symbolizer_unittest.cc
- src/profiling/symbolizer/filesystem.h
- src/profiling/symbolizer/filesystem_windows.cc
- src/profiling/symbolizer/local_symbolizer.h
- src/profiling/symbolizer/symbolizer.h
- src/trace_processor/importers/common/mapping_tracker.cc
- src/trace_processor/importers/common/virtual_memory_mapping.cc
- src/trace_processor/importers/perf/features.cc
- src/trace_processor/importers/perf/features.h
- src/trace_processor/importers/perf/perf_data_tokenizer.cc
Just some pre-work before I touch these files.
> symbolizer: tp: minor cleanups to namespaces and includes

- .github/workflows/gemini-cli.yml
- .github/workflows/gemini-issue-automated-triage.yml
- .github/workflows/gemini-issue-scheduled-triage.yml
- .github/workflows/gemini-pr-review.yml
No custom changes, all comes directly from gemini cli command
> perfetto: run /setup-github to get latest gemini github action files

- ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.scss
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_box.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_issues.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/aggregation_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/slices_source.scss
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/slices_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/sql_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/table_source.scss
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/table_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sub_query_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_builder_utils.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
SQL nodes support aggregations and filtering in sub nodes
Added more robust warnings and errors to nodes
> exp: Better warnings and support for aggregating SQL node

- src/trace_processor/perfetto_sql/stdlib/viz/slices.sql
- ui/src/plugins/dev.perfetto.TraceProcessorTrack/index.ts
Allows matching the pivot table
> ui: add simple slice count to slice flamegraph

- ui/src/core/settings_manager.ts
- ui/src/frontend/home_page.ts
- ui/src/public/settings.ts
> ui: Add dark mode switch on homepage

- ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/data_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_explorer.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/aggregation_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/slices_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/sql_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/table_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sub_query_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/source_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
When the SQL node changed and had Agg node attached, the Agg node group by columns were not updated. This is a fix
Also cleaned up the messy sourceCols logic
> exp: Fix Agg behaviour when the SQL is changing

- ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/graph.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_box.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/aggregation_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/interval_intersect_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/sql_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/table_source.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sub_query_node.ts
- ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
Add support for interval intersect node and support for multiple child nodes
> exp: Add interval intersect node

- src/trace_processor/util/tar_writer.cc
GetFileSize needs a platformhandle on windows which we cannot acquire
easily
Fixes: b/441903888
> tp: fix build on Windows

- src/trace_processor/util/tar_writer.cc
- src/trace_processor/util/tar_writer.h
- src/trace_processor/util/tar_writer_unittest.cc
Blind CL doing waht I think will work.
> tp: attempt to fix TarWriter test failures on windows

- src/trace_processor/metrics/sql/android/jank/cujs_boundaries.sql
- src/trace_processor/metrics/sql/android/jank/frames.sql
- src/trace_processor/metrics/sql/android/jank/relevant_slices.sql
- src/trace_processor/perfetto_sql/stdlib/android/cujs/sysui_cujs.sql
Considering multiple use-cases for this table, moving it to stdlib for common usage.
Bug: 441860507
> Add table containing Choreographer#doFrame within CUJs to stdlib.

- src/trace_processor/perfetto_sql/stdlib/linux/perf/samples.sql
- ui/src/plugins/dev.perfetto.CpuProfile/index.ts
Matches what we do for perf, heapp profiles, heap dumps etc.
> tp: automatically select cpu profiles on startup

- src/trace_processor/perfetto_sql/stdlib/export/to_svg.sql
- Refactor complex nested logic into flat CTEs for readability
> stdlib: Fix division by zero in SVG generation

- ui/src/plugins/com.android.AndroidLongBatteryTracing/index.ts
> Show jobs based on statsd atoms if available rather than battery stats.

- src/trace_processor/perfetto_sql/stdlib/android/cpu/cpu_per_uid.sql
- src/trace_processor/perfetto_sql/stdlib/counters/intervals.sql
Also, add some documentation that states that.
Bug: http://b/422976190
> Don't use delta_value in CPU per UID, it's lagging.

- gn/perfetto.gni
- include/perfetto/ext/base/flags.h
- include/perfetto/ext/base/rt_mutex.h
- perfetto_flags.aconfig
- src/base/rt_mutex.cc
- src/base/rt_mutex_benchmark.cc
- src/base/rt_mutex_unittest.cc
> base: Reland RTFutex for android

- Android.bp
- BUILD
- src/trace_processor/importers/proto/winscope/BUILD.gn
- src/trace_processor/importers/proto/winscope/viewcapture_visibility_computation.cc
- src/trace_processor/importers/proto/winscope/viewcapture_visibility_computation.h
- src/trace_processor/importers/proto/winscope/viewcapture_visibility_computation_unittest.cc
Bug: 438683146
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=ViewCapture*
> tp: Compute visibility for viewcapture views.

- Android.bp
- BUILD
- include/perfetto/ext/base/BUILD.gn
- include/perfetto/ext/base/dynamic_string_writer.h
- src/base/BUILD.gn
- src/base/dynamic_string_writer_unittest.cc
Add DynamicStringWriter, a counterpart to FixedStringWriter, which can be used in cases when the string can be arbitrary large.
> Add DynamicStringWriter

- ui/release/channels.json
> ui: Roll canary

- include/perfetto/ext/base/scoped_file.h
- src/base/file_utils.cc
- src/base/subprocess_windows.cc
- src/base/task_runner_benchmark.cc
- src/base/thread_checker.cc
- src/bigtrace/orchestrator/orchestrator_impl.cc
This pull requests contains various performance improvements found using cppcheck.
Most of the fixes include passing parameters by reference, where feasible, as well as initializing class members in their initialization list.
> Various cppcheck performance fixes

- src/profiling/perf/regs_parsing.cc
The change to increase the memcpy already covers setting the sp/pc.
> Actually remove redundant setting of sp/pc.

- gn/standalone/sanitizers/ignorelist.txt
- src/traced/probes/filesystem/file_scanner.cc
- src/traced/probes/filesystem/file_scanner_unittest.cc
> perfetto: fix msan failures

- src/trace_processor/importers/proto/frame_timeline_event_parser.cc
- src/trace_processor/importers/proto/frame_timeline_event_parser.h
- ui/src/plugins/dev.perfetto.Frames/index.ts
This make debugging the new classification more easy
> Show an additional track for experimental jank classification for a side-by-side comparison 

- ui/src/components/tracks/base_counter_track.ts
Fixes: https://github.com/google/perfetto/issues/3204
> ui: allow 2x enlarging of counter tracks
