infra/perfetto.dev/cloud_build_entrypoint.sh
infra/ui.perfetto.dev/builder/Dockerfile
infra/ui.perfetto.dev/builder/ui_builder_entrypoint.sh

Remove the old code that was using GitHub only as a trigger and then pulling from AOSP.
Bug: b/406181088

ui: change ui_builder_entrypoint to reference GitHub

---

ui/src/components/tracks/base_counter_track.ts

Fix counter hover in log mode; we were previously showing the log value in the hover.

Fix counter hover in log mode

---

src/tracing/service/tracing_service_impl.cc
src/tracing/service/tracing_service_impl_unittest.cc

Reading a cloned trace with a trigger we found many (many) absolutely identical packets like:
```
packet {
trusted_uid: 9999
timestamp: 223437728327805
trusted_packet_sequence_id: 1
clone_snapshot_trigger {
trigger_name: "..."
producer_name: "perfetto_cmd_producer"
trusted_producer_uid: 10134
}
}
```
It turns out TracingServiceImpl is emitting them on every ReadBuffers(). This is not required, let'd to like we do it MaybeEmitTraceConfig().
Bug: 406599194

tracing_service_impl: Only emit clone_snapshot_trigger once

---

protos/perfetto/trace/chrome/chrome_trace_packet.proto

We didn't catch this because we don't build the chrome protos (.../trace/chrome:minimal_complete_lite). Let's consider putting that in presubmit, but I wanted to keep this patch minimal
Fixes: 94a1b58c6e ("protos: remove ProfiledFrameSymbols")
Bug: 406928883

protos: remove unused import (profile_common.proto)

---

ui/src/core/app_impl.ts
ui/src/core/trace_impl.ts
ui/src/public/app.ts
ui/src/public/route_schema.ts

Any route args that are formatted like:
```
<pluginId>:<key>=<value>
```
will be redirected to the plugin with id `<pluginId>`.
Plugins can access their args via `app.initialPluginRouteArgs`.
https://b.corp.google.com/issues/406308446

ui: Parse out any plugin specific route args and direct them to plugins

---

Android.bp
tools/gen_android_bp

A cc_library can also be statically linked, and that might be required for the soong `libandroid_runtime` target on host.

Android.bp: Change libperfetto_c from cc_library_shared to cc_library

---

src/tools/ftrace_proto_gen/ftrace_proto_gen.cc
src/tools/ftrace_proto_gen/ftrace_proto_gen.h
src/tools/ftrace_proto_gen/main.cc
src/tools/ftrace_proto_gen/proto_gen_utils.cc
src/tools/ftrace_proto_gen/proto_gen_utils.h
src/traced/probes/ftrace/atrace_hal_wrapper.h
src/traced/probes/ftrace/compact_sched.h
src/traced/probes/ftrace/cpu_stats_parser_unittest.cc
src/traced/probes/ftrace/event_info.h
src/traced/probes/ftrace/event_info_constants.h
src/traced/probes/ftrace/format_parser/format_parser.cc
src/traced/probes/ftrace/format_parser/format_parser.h
src/traced/probes/ftrace/ftrace_config_muxer.cc
src/traced/probes/ftrace/ftrace_controller.cc
src/traced/probes/ftrace/ftrace_controller.h
src/traced/probes/ftrace/ftrace_data_source.h
src/traced/probes/ftrace/ftrace_print_filter.cc
src/traced/probes/ftrace/ftrace_stats.h
src/traced/probes/ftrace/proto_translation_table.cc
src/traced/probes/ftrace/proto_translation_table.h
src/traced/probes/ftrace/test/cpu_reader_support.cc
src/traced/probes/probes_producer.cc
src/traced/probes/probes_producer.h
src/traced_relay/relay_service_integrationtest.cc
test/android_integrationtest.cc
test/cmdline_integrationtest.cc
test/end_to_end_benchmark.cc
test/ftrace_integrationtest.cc
test/traced_integrationtest.cc

Small cleanups separated from an upcoming feature in ftrace code. Mostly
to get clangd off my back, and in retrospect I'm just disabling most of
the tidy checks locally until presubmit.

tprobes: clang-tidy/readability cleanups

---

src/trace_processor/importers/proto/track_event_tokenizer.cc

Instead just increment a stat
Fixes: b/405989882

tp: don't hard-error when unable to parse v8 sample

---

include/perfetto/tracing/data_source.h

Fixes https://github.com/google/perfetto/issues/1107

Fixing unused variable warning in PERFETTO_INTERNAL_SWALLOW_SEMICOLON()

---

ui/src/base/hotkeys.ts

The hotkey for "Go to next slice" is ".", but the "." key cannot be pressed without holding shift on AZERTY keyboards. Perfetto doesn't recognize the hotkey because "Shift+." is a different hotkey.
A while ago we set up a fix for this scenario, by listing a bunch of keys that cannot be pressed either with or without holding the shift key. In this scenario we ignore the shift key. This PR simply adds "." and "," to this list.
Fixes #1113

ui: Fix  go to next slice hotkey not working on AZERTY

---

.github/workflows/analyze.yml
.github/workflows/pr-branch-check.yml

My previous attempt of putting it into analyze turned out to be useless. I need to specify the job name under the ruleset anyways.
This is better because the check shows up wiht a better than rather than "Perfetto CI"

CI: re-move PR check into its own workflow

---

.github/workflows/require-two-reviewers-for-fork-prs.yml

Trigger on pull-request review activity, not on upload.
Also run on our bots, not on the communal quota.

CI: improve 2-reviewer check

---

src/trace_processor/dataframe/dataframe.cc
src/trace_processor/dataframe/dataframe.h
src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/bytecode_instructions.h
src/trace_processor/dataframe/impl/bytecode_interpreter.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/impl/query_plan.h
src/trace_processor/dataframe/impl/slab.h
src/trace_processor/dataframe/impl/types.h
src/trace_processor/dataframe/specs.h

This PR adds support for both null overlays on columns and the
isnull and isnotnull operators on all columns.

df: add support for null overlays and isnull/isnotnull

---

src/trace_processor/perfetto_sql/stdlib/android/memory/dmabuf.sql

Not sure how this slipped, we used to join the slice id with the track id.
Bug: b/407981171

Fix dmabuf slice tracking query

---

src/trace_processor/perfetto_sql/stdlib/wattson/cpu_freq.sql
src/trace_processor/perfetto_sql/stdlib/wattson/cpu_idle.sql

Exclude slices with duration of 0 in the initial freq and idle tables used during Wattson calculation. Removing the dur==0 slices is necessary since a requirement for interval_intersect() is that the input have non-zero slices duration.
A dur==0 freq or idle slice can occur in the rare case when a trace has a freq or idle ftrace event at the same timestamp as trace_end().
Bug: 408009977
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter '.*wattson.*'

stdlib: Exclude dur==0 in Wattson freq/idle tables

---

Android.bp
BUILD
src/trace_processor/dataframe/BUILD.gn
src/trace_processor/dataframe/cursor.h
src/trace_processor/dataframe/dataframe.cc
src/trace_processor/dataframe/dataframe.h
src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/bit_vector.h
src/trace_processor/dataframe/impl/bit_vector_unittest.cc
src/trace_processor/dataframe/impl/bytecode_instructions.h
src/trace_processor/dataframe/impl/bytecode_interpreter.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc
src/trace_processor/dataframe/impl/flex_vector.h
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/impl/query_plan.h
src/trace_processor/dataframe/impl/types.h
src/trace_processor/dataframe/runtime_dataframe_builder.h
src/trace_processor/dataframe/runtime_dataframe_builder_unittest.cc
src/trace_processor/dataframe/specs.h
src/trace_processor/dataframe/type_set.h
src/trace_processor/perfetto_sql/engine/dataframe_module.cc
src/trace_processor/perfetto_sql/engine/dataframe_module.h

This CL adds a builder class for building dataframes where the schema of the
dataframe is not known upfront and should be inferred from the inserted
rows. We try and always be as memory efficient as possible and infer as many
properties (i.e. sorted/id etc) as we can.

df: add runtime builder class for building dataframes for unknown schemas

---

Android.bp
BUILD
src/android_sdk/java/main/BUILD.gn
src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrace.java
src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrackEventBuilder.java
src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrackEventExtra.java
src/android_sdk/java/test/dev/perfetto/sdk/test/PerfettoTraceTest.java

We decouple the event builder from the native object wrappers, that simplifies the code and allows us to enable the debug asserts in builder at runtime.
Tested:
```
tools/bazel test //:src_android_sdk_java_test_perfetto_trace_instrumentation_test
```

Perfetto Android Java SDK: extract 'PerfettoTrackEventBuilder'.

---

src/tracing/core/shared_memory_arbiter_impl.cc

These are totally harmless logs but they confuse poeople a lot when they appear. See http://yaqs/1389768403857702912

tracing: remove logspam from stalling messages

---

PRESUBMIT.py
tools/run_presubmit

This was introduced in 0fd92a9496e0("service: disallow ReadBuffers for CLONE_SNAPSHOT traces"), but it never worked.
I checked the current complaints and they're all false positives.
I'm also removing the check from PRESUBMIT.py, even though this should not be used anymore.

Remove obsolete CheckBadCppPatterns from tools/run_presubmit

---

ui/src/frontend/post_message_handler.ts
ui/src/frontend/post_message_handler_unittest.ts

This builds on f2511be5e0c05976ccb5233edfa8ee2141923731 to extend support for trusted origins to `*.proxy.googlers.com` hostnames, which are used in addition to `*.c.googlers.com` hostnames.
I extended the unit tests to cover this and confirmed the tests pass with `./ui/run-unittests`.
Bug: http://b/402495918

[ui] Extend trusted origin to support *.proxy.googlers.com hostnames

---

src/base/test/vm_test_utils.cc

Some of the chromium bots were not happy after the headers inclusion order was changed after clang-format.
Reverting back the orders in which the headers are added, and turning off clang format for the block where headers are added.
Bug: b/409239273

Include Psapi.h after Windows.h

---

.github/workflows/android-tests.yml
.github/workflows/fuzzer-tests.yml
.github/workflows/linux-tests.yml

the cc_wrapper=ccache got lost in the CI rewrite.
UI workflow was the only one actually using ccache because build.js automatically enables it while invoking GN by itself. Adding GN args to the other bots

CI: actually use ccache

---

ui/src/core_plugins/track_utils/index.ts

This PR adds a 'Dvorak keyboard layout' flag which disables:
- '.' hotkey to go to the next slice
- ',' hotkey to go to the previous slice
This approach is a quick fix. The proper fix is to allow users to configure hotkeys, but we're a long way off this.

ui: Add flag to patch around hotkey collisions in dvorak

---

src/trace_processor/importers/proto/winscope/shell_transitions_parser.cc
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.cc
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.h
src/trace_processor/importers/proto/winscope/winscope_module.cc
src/trace_processor/importers/proto/winscope/winscope_module.h
test/trace_processor/diff_tests/parser/android/args_table_issue.textproto
test/trace_processor/diff_tests/parser/android/tests_shell_transitions.py

This is to fix an issue where ShellTransition data was not being correctly parsed by the parser resulting in missing data in the transitions in Flicker and Winscope. The was due to a misuse of the ArgsTracker interface in the ShellTransitionsParser, where the args were being overwritten with new arg sets due to the flushing of the `context->args_tracker` that was happening every once in a while. We should now be accumulating the args correctly and fully before flushing them to storage, ensuring we don't miss any args in the trace tables.
Bug: 406973318
Test: tools/diff_test_trace_processor.py out/linux_clang_debug/trace_processor_shell --name-filter=".*Transition.*"
Change-Id: I74728cb062066468dd80f5aa6315e7e15316343e

Update TransitionsTracker to use own ArgsTracker instances

---

include/perfetto/ext/trace_processor/importers/memory_tracker/raw_memory_graph_node.h
src/trace_processor/importers/memory_tracker/raw_memory_graph_node.cc

In `RawMemoryGraphNode`, make some string constants `static constexpr`.
This is apparently only a problem in ASan component builds.
Bug: 408927257

trace_processor: Fix ODR violations

---

src/trace_processor/trace_summary/summary.cc

Tested using the chrome_histogram_metrics.textproto:
```
query {
id: "chrome_histogram_summaries"
sql: {
column_names: "histogram_name"
column_names: "average"
column_names: "sum"
column_names: "max"
column_names: "min"
column_names: "count"
sql:
"
with chrome_histogram_slices as
(
select
*,
extract_arg(arg_set_id, 'chrome_histogram_sample.name') as histogram_name,
extract_arg(arg_set_id, 'chrome_histogram_sample.sample') as histogram_sample
from slice
where category = 'disabled-by-default-histogram_samples'
)
select
process.name as process_name,
pid,
histogram_name,
count(1) as count,
sum(histogram_sample) as sum,
max(histogram_sample) as max,
min(histogram_sample) as min,
avg(histogram_sample) as average
from chrome_histogram_slices _cslice
join thread_track on _cslice.track_id = …
```

tp: fix internal syntax error in v2 metric using shared query

---

ui/src/assets/perfetto.scss
ui/src/assets/viewer_page.scss
ui/src/assets/widgets/tooltip.scss
ui/src/components/tracks/base_slice_track.ts
ui/src/frontend/viewer_page/track_tree_view.ts
ui/src/frontend/viewer_page/track_view.ts
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/public/track.ts
ui/src/widgets/cursor_tooltip.ts

Using the DOM for tooltips has the following benefits:
- Tooltips can be larger than the track
- Can add more detailed information
- Much easier to style
These tooltips use a new widget called `CursorTooltip`, which uses `popper.js` to automatically flip sides to keep the tooltip visible - just like the `Popup` widget does.

Render slice tooltips to the DOM (instead of to the canvas)

---

tools/run_presubmit

I've found myself fighting this presubmit in ftrace sources because we have cases with tabs inside test strings (as extracted from tracefs).
Since we're now enforcing formatting, and clang-format covers tabs in cpp sources, exclude them from this presubmit check.

presubmit: let clang-format handle tabs in cpp sources

---

ui/src/plugins/dev.perfetto.PowerAggregations/index.ts
ui/src/plugins/dev.perfetto.PowerAggregations/power_counter_selection_aggregator.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/index.ts
ui/src/public/track.ts

Add power specific aggregation to provide better UX when clicking and dragging over power samples.
issue: https://github.com/google/perfetto/issues/910
Screenshot of test/data/power_rails.pb:

Add power-specific selection aggregation

---

src/trace_processor/dataframe/dataframe.cc
src/trace_processor/dataframe/dataframe.h
src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/bytecode_core.h
src/trace_processor/dataframe/impl/bytecode_instructions.h
src/trace_processor/dataframe/impl/bytecode_interpreter.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/impl/query_plan.h
src/trace_processor/dataframe/impl/types.h
src/trace_processor/dataframe/runtime_dataframe_builder_unittest.cc
src/trace_processor/dataframe/specs.h
src/trace_processor/perfetto_sql/engine/dataframe_module.cc

This PR adds end to end support for sorting dataframes; all the way from
SQLite to the interpreter.

tp: add support for sorting dataframes

---

ui/src/assets/viewer_page.scss
ui/src/components/tracks/base_slice_track.ts
ui/src/components/tracks/dataset_slice_track.ts
ui/src/plugins/dev.perfetto.AndroidLog/logs_track.ts
ui/src/plugins/dev.perfetto.HeapProfile/heap_profile_track.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/trace_processor_slice_track.ts

Allow users of DatasetSliceTrack to entirely override what's shown on the tooltip & add `category` if not null

Allow users of DatasetSliceTrack to entirely override what's shown on the tooltip

---

python/tools/code_format_ui.py
tools/run_presubmit

- Don't run eslint/prettier outside of ui/. Thei fail with a warning if you try because they assume ui/ as root.
- Allow tabs in Makefile because they are load bearing

presubmit: minor fixes

---

ui/src/core/default_plugins.ts

The power aggregations tab provides users a better UX when
aggregating over power rail. Enable this plugin by default so that
users get this better UX without having to enable the plugin
manually.

[ui] Enable power aggregation tab plugin by default

---

ui/src/components/aggregation_adapter.ts
ui/src/plugins/dev.perfetto.PowerAggregations/index.ts

Display the power-specific aggregation by default instead of the
generic aggregation tab in order provide the user a better UX when
aggregating over power rail tracks.
example: 
Bug: https://github.com/google/perfetto/issues/910

[ui] prioritize display of power-specifc aggregation

---

src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/bytecode_instructions.h
src/trace_processor/dataframe/impl/bytecode_interpreter.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/impl/query_plan.h
src/trace_processor/dataframe/impl/types.h

When we get an order by + limit 1 we can optimize it to just be a min/max on the column

tp: add support for min/max optimization

---

ui/src/assets/viewer_page.scss
ui/src/widgets/cursor_tooltip.ts

This more closely resembles the previous canvas based tooltips, and keeps the tooltips out the way of neighboring tracks

Make DOM tooltips smaller and align them to center right of cursor

---

include/perfetto/ext/base/string_utils.h
src/base/string_utils.cc
src/base/string_utils_unittest.cc
src/trace_processor/importers/systrace/systrace_parser.cc
src/trace_processor/importers/systrace/systrace_parser.h
src/trace_processor/importers/systrace/systrace_parser_unittest.cc

Remove non UTF-8 characters in systrace parser
A trace can contain some "bytes" in "print" ftrace events which are not valid UTF8. sqlite expects strings to be UTF-8.
Tested via
```
tools/ninja -C out/linux_clang_debug && out/linux_clang_debug/perfetto_unittests &&  tools/diff_test_trace_processor.py  out/linux_clang_debug/trace_processor_shell
```

Remove non UTF-8 characters in systrace parser

---

src/trace_redaction/filtering.cc
src/trace_redaction/filtering.h
src/trace_redaction/redact_process_events.cc
src/trace_redaction/redact_process_events.h
src/trace_redaction/redact_process_events_unittest.cc

Before this, redaction relied on the `pid` value in the rename task and asserted its presence. This broke when Perfetto stopped emitted the field. The field was removed because the rename task's `pid` would match the ftrace event's `pid`.
To safely remove the assertion, redaction will now use:
```
return rename_task.has_pid() ? rename_task.pid() : ftrace_event.pid()
```

Redaction - Use ftrace event `pid` with rename events

---

protos/perfetto/config/ftrace/ftrace_config.proto
protos/perfetto/config/perfetto_config.proto
protos/perfetto/trace/ftrace/ftrace_event.proto
protos/perfetto/trace/ftrace/ftrace_event_bundle.proto
protos/perfetto/trace/perfetto_trace.proto
src/tools/ftrace_proto_gen/ftrace_proto_gen.cc
src/traced/probes/ftrace/cpu_reader.cc
src/traced/probes/ftrace/cpu_reader.h
src/traced/probes/ftrace/cpu_reader_benchmark.cc
src/traced/probes/ftrace/cpu_reader_fuzzer.cc
src/traced/probes/ftrace/cpu_reader_unittest.cc
src/traced/probes/ftrace/ftrace_config_muxer.cc
src/traced/probes/ftrace/ftrace_config_muxer.h
src/traced/probes/ftrace/ftrace_config_muxer_unittest.cc
src/traced/probes/ftrace/proto_translation_table.cc
src/traced/probes/ftrace/proto_translation_table.h
src/traced/probes/ftrace/proto_translation_table_unittest.cc
src/traced/probes/ftrace/test/data/synthetic_alt/events/generic/sched_switch_generic/format
src/traced/probes/ftrace/test/data/synthetic_alt/events/generic/sched_waking_generic/format

Using "descriptor" as a proto field complicates code generation in at
least google3-java. Hence s/descriptor/event_descriptor/.
-- original commit (80fa299) --
The encoding of ftrace events that do not have a protobuf description in
the perfetto repo is very space inefficient. This is because every
GenericFtraceEvent proto has a string description of the field names and
added layers of proto nesting. This was good enough for local
exploration, but is often used by accident when configs use category
globs. Also, long-term it'd be nice to move away from requiring protos
to be checked into our repo outside of truly well-known cases.
This patch adds a feature flag to enable such generic events to be
serialised using self-describing protos, with the aim of being a bit
more space efficient. The …

reland 80fa299: tprobes: generic events as self-describing protos (2/2) (#1225)

---

docs/reference/synthetic-track-event.md

The UI crashes when selecting an unnamed instant.
Bug: 410329414

docs: track-event: fix missing instant event name in example + misc fixups

---

docs/reference/synthetic-track-event.md

Lowercase for these events is actually correct

docs: fix typos

---

gn/standalone/BUILD.gn
infra/luci/recipes/perfetto.expected/ci_win.json
infra/luci/recipes/perfetto.py
tools/install-build-deps

It doesn't work on windows. Luckily the venv is not required for building, only when changing the source code.
Partially autogenerated by running
`cd infra/luci && ./recipes.py test train`.

luci: Avoid installing python venv

---

ui/src/base/mithril_utils.ts
ui/src/core/page_manager.ts
ui/src/core/router.ts
ui/src/core_plugins/flags_page/flags_page.ts
ui/src/core_plugins/flags_page/index.ts
ui/src/core_plugins/flags_page/plugins_page.ts
ui/src/frontend/home_page.ts
ui/src/frontend/index.ts
ui/src/frontend/ui_main.ts
ui/src/frontend/viewer_page/viewer_page.ts
ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
ui/src/plugins/dev.perfetto.ExplorePage/index.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/data_source_viewer.ts
ui/src/plugins/dev.perfetto.InsightsPage/index.ts
ui/src/plugins/dev.perfetto.InsightsPage/insights_page.ts
ui/src/plugins/dev.perfetto.MetricsPage/index.ts
ui/src/plugins/dev.perfetto.MetricsPage/metrics_page.ts
ui/src/plugins/dev.perfetto.QueryPage/index.ts
ui/src/plugins/dev.perfetto.QueryPage/query_page.ts
ui/src/plugins/dev.perfetto.RecordTraceV2/index.ts
ui/src/plugins/dev.perfetto.RecordTraceV2/pages/record_page.ts
ui/src/plugins/dev.perfetto.TraceInfoPage/index.ts
ui/src/plugins/dev.perfetto.TraceInfoPage/trace_info_page.ts
ui/src/plugins/dev.perfetto.VizPage/index.ts
ui/src/plugins/dev.perfetto.VizPage/viz_page.ts
ui/src/plugins/dev.perfetto.WidgetsPage/index.ts
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/public/page.ts

In order to register a page plugins currently need to provide a component whose attributes extend the `PageWithTraceAttrs` interface, unless the magic `traceless` flag is passed at which point they need only pass a component whose attributes extend the `PageAttrs` interface.
This is confusing for a number of reasons. How is the trace passed in to the page? What about the app? How do I pass my own arguments into my page?
Consider tracks and tabs for example, Any Mithril rendering done by those entities is described using functions, which are simply called every render cycle (when relevant). Usage of a function allows crucial arguments such as trace/app/etc to be captured using a closure, and any 'this' context to be captured simply by using an arrow function. 
The page API, however, takes …

Tidy up page registration

---

ui/src/plugins/dev.perfetto.RecordTraceV2/pages/android.ts

This ensures the package_list is recored when network tracing is enabled in the record V2 ui. This is the typical use case, to ensure that the packets are reported with their associated package name.

Record package_list when network tracing is enabled

---

Android.bp
BUILD
protos/perfetto/trace/android/kernel_wakelock_data.proto
protos/perfetto/trace/perfetto_trace.proto
src/kernel_utils/BUILD.gn
src/kernel_utils/kernel_wakelock_errors.h
src/trace_processor/importers/proto/BUILD.gn
src/trace_processor/importers/proto/android_kernel_wakelocks_module.cc
src/trace_processor/storage/stats.h
src/traced/probes/android_kernel_wakelocks/BUILD.gn
src/traced/probes/android_kernel_wakelocks/android_kernel_wakelocks_data_source.cc

Bug: 404239369
We're seeing rare, strange results in traces that are consistent with SuspendControlService rolling back values or returning 0. If we see this occurring, ignore what it told us and increment a counter.

Detect, ignore, and log weird results from SuspendControlService.

---

src/trace_processor/importers/common/legacy_v8_cpu_profile_tracker.cc
src/trace_processor/importers/common/legacy_v8_cpu_profile_tracker.h
src/trace_processor/importers/json/json_trace_tokenizer.cc
src/trace_processor/importers/proto/track_event_tokenizer.cc
src/trace_processor/storage/stats.h

Turns out they use a separate format to V8 with a more standardised
system [1]. Since supporting it is quite simple, just do it.
See discussion at https://github.com/google/perfetto/issues/275 for what prompted this.
[1] https://chromedevtools.github.io/devtools-protocol/tot/Profiler/#type-ProfileNode

tp: fix parsing of Chrome Devtools/NodeJS CPU profiling data

---

ui/src/assets/perfetto.scss
ui/src/assets/widgets/settings_shell.scss
ui/src/core_plugins/flags_page/plugins_page.ts
ui/src/widgets/settings_shell.ts

The widget `SettingsPage` was badly named, and will collide with the upcoming (actual) settings page!
This PR just renames this widget to `SettingsShell` which more accurately describes what the widget does and will cause less confusion when we have a real settings page.

Renamed SettingsPage -> SettingsShell

---

ui/src/core/feature_flags.ts
ui/src/core/feature_flags_unittest.ts
ui/src/core/local_storage.ts
ui/src/core/storage.ts

- Move the `Storage` abstraction out of feature_flags.ts into its own file.
- Add ability to inject a local storage key into `LocalStorage` implementation, which allows it to be reused for other systems that require local storage, not just flags.
- Refactor feature flags & tests accordingly.

Move feature flags `storage` abstraction to new file & make reusable

---

Android.bp
BUILD
protos/perfetto/config/system_info/BUILD.gn

This is not necessary as the system_info_config does not depend on
anything in common.

protos: remove redundant edge

---

ui/src/core/dataset_search.ts
ui/src/core/search_manager.ts

This change improves efficiency of the dataset search algorithm by grouping together batches of tracks that have the same dataset `src` running one query per group, rather than a big union all of all tracks.
In addition, rather than embedding the track URI in the query, we resolve the owning track for each event by doing a reverse lookup of the track's partition (filter).
This leads to much more efficient query(s), despite having to run more than one query (one per track group).

Improve dataset search efficiency

---

src/android_sdk/jni/dev_perfetto_sdk_PerfettoNativeMemoryCleaner.cc
src/android_sdk/jni/dev_perfetto_sdk_PerfettoNativeMemoryCleaner.h
src/android_sdk/jni/dev_perfetto_sdk_PerfettoTrace.cc
src/android_sdk/jni/dev_perfetto_sdk_PerfettoTrackEventExtra.cc
src/android_sdk/jni/dev_perfetto_sdk_PerfettoTrackEventExtra.h

To be consistent with the new 'dev.perfetto.sdk' package and the ".cpp"/".h" file names.

Rename 'android_os_Perfetto*' JNI functions to 'dev_perfetto_sdk_Perfetto*'.

---

include/perfetto/ext/base/http/http_server.h
include/perfetto/ext/base/unix_socket.h
src/base/http/http_server.cc
src/base/unix_socket.cc
src/trace_processor/rpc/httpd.cc
src/trace_processor/rpc/httpd.h
src/trace_processor/trace_processor_shell.cc

make trace_processor_shell support listen on specific ip other than localhost.
issuse: https://github.com/google/perfetto/issues/1181
users can use --http-ip 0.0.0.0 to specific an ip or a hostname.  
trace_processor_shell will listen on 0.0.0.0 by default.
this make it can be accessed by localhost:9001 even trace_processor_shell is started at a docker container by port forward.
like this: docker run -it --rm   -p 9001:9001 image:tag trace_processor_shell -D --http-port 9001

tp: support listening on specified ip

---

ui/src/plugins/dev.perfetto.HeapProfile/heap_profile_details_panel.ts

A missing return was invalidating the dialog and
falling through anyways.

ui: fix graceful dialog on downloadPprof

---

protos/perfetto/trace/perfetto_trace.proto
protos/perfetto/trace/track_event/chrome_frame_reporter.proto
protos/perfetto/trace/track_event/track_event.proto

It was replaced with the `ChromeFrameReporter2` message in the Chromium repostitory so that its source of truth would be with the rest of the Chromium source code. The `TrackEvent.chrome_frame_reporter` field was further replaced with the `ChromeTrackEvent.frame_reporter` extension.
Bug: https://crbug.com/409484302

Mark ChromeFrameReporter as deprecated

---

include/perfetto/ext/tracing/core/tracing_service.h
src/profiling/memory/heapprofd_producer.cc
src/profiling/perf/perf_producer.cc
src/traced/probes/probes_producer.cc
src/traced/service/builtin_producer.cc
src/tracing/service/tracing_service_impl_unittest.cc
src/tracing/test/proxy_producer_endpoint.h
src/tracing/test/tracing_integration_test.cc
test/end_to_end_shared_memory_fuzzer.cc
test/fake_producer.cc

Default arguments are banned in virtual functions by the Google C++ style.
I didn't find any use of the default argument outside of the perfetto repo.

Remove default argument from ProducerEndpoint::CreateTraceWriter

---

include/perfetto/ext/tracing/core/shared_memory_arbiter.h
include/perfetto/ext/tracing/core/tracing_service.h
src/profiling/memory/heapprofd_producer.cc
src/profiling/perf/perf_producer.cc
src/traced/probes/probes_producer.cc
src/traced/service/builtin_producer.cc
src/tracing/core/shared_memory_arbiter_impl.h
src/tracing/core/shared_memory_arbiter_impl_unittest.cc
src/tracing/core/trace_writer_impl_unittest.cc
src/tracing/service/tracing_service_impl_unittest.cc
src/tracing/test/proxy_producer_endpoint.h
src/tracing/test/tracing_integration_test.cc
test/end_to_end_shared_memory_fuzzer.cc
test/fake_producer.cc

Default arguments are banned in virtual functions by the Google C++ style.
I didn't find any use of the default argument outside of the perfetto repo.

Remove default argument from SharedMemoryArbiter::CreateTraceWriter

---

include/perfetto/ext/tracing/core/shared_memory_arbiter.h
include/perfetto/ext/tracing/core/tracing_service.h
include/perfetto/tracing/buffer_exhausted_policy.h
src/profiling/memory/heapprofd_producer.cc
src/profiling/perf/perf_producer.cc
src/traced/probes/probes_producer.cc
src/traced/service/builtin_producer.cc
src/tracing/core/shared_memory_arbiter_impl.h
src/tracing/core/shared_memory_arbiter_impl_unittest.cc
src/tracing/core/trace_writer_impl_unittest.cc
src/tracing/service/tracing_service_impl_unittest.cc
src/tracing/test/mock_producer.h
src/tracing/test/proxy_producer_endpoint.h
src/tracing/test/tracing_integration_test.cc
test/end_to_end_shared_memory_fuzzer.cc
test/fake_producer.cc

The default in the SDK data sources is actually kDrop. As the TODO says, we always wanted to change it.
Let's mark the alias as deprecated.

Deprecate BufferExhaustedPolicy::kDefault enum alias

---

ui/src/frontend/viewer_page/track_view.ts
ui/src/plugins/dev.perfetto.AndroidLog/index.ts
ui/src/public/track.ts

This PR adds track descriptions to track definitions.
Plugins can attach descriptions (short strings of text) that are displayed in the track details popup.
In the future we could make this style of help text more visible and more consistent throughout the UI, but for now this change provides the plumbing to allow plugins to specify descriptions.

Add track descriptions

---

ui/src/core/settings_manager.ts
ui/src/core/trace_impl.ts
ui/src/plugins/com.example.Settings/index.ts
ui/src/public/settings.ts

Fixes a bug where settings added via the trace object (inside the onTraceLoad() function for example) are not removed when a second trace is loaded, and thus we run into a crash when the duplicate setting is added.

Dispose trace-scoped settings properly when the trace is disposed

---

tools/roll-prebuilts

yapf is not assumed to be on the PATH anymore. python code should be formatted later (after gen_amalgamated_python_tools) with tools/format-python-sources.

tools/roll-prebuilts: Avoid calling yapf

---

src/trace_processor/dataframe/dataframe_unittest.cc

dataframe is quite a large object because of the arrays, allocate on
heap to avoid crashes.

tp: move dataframe onto heap to avoid potential overflows

---

ui/src/widgets/text_input.ts

Ensure that the class name is passed properly to a TextInput div
rather than being passed as a string child element.

[ui] Fix passing classes to input elements

---

include/perfetto/public/abi/data_source_abi.h
include/perfetto/tracing/buffer_exhausted_policy.h
src/shared_lib/data_source.cc
src/tracing/core/shared_memory_arbiter_impl.cc
src/tracing/core/trace_writer_impl.cc

The new policy is useful where the data source wants to avoid data loss as much as possible, but doesn't want to crash the process if the tracing service is not responsive.
Tested: unsubmitted (it wastes 20 seconds) integration test

tracing: New stall buffer exhausted policy

---

gn/standalone/BUILD.gn
gn/standalone/toolchain/BUILD.gn
gn/standalone/toolchain/llvm.gni

On Linux, when NOT using clang, we used to depend on the gold linker. That linker is now going away, making this problematic. We realistically don't care about it, because all our reference builds (both on Android and linux) use the hermetic clang toolchain.
I tested that this change has only effect on the gcc build configs, as follows:
- Run tools/setup_all_configs.py --android
- cp -a out out.old
- Apply this patch
- cd out; for x in *; do gn gen $x; done
- git diff --no-index --word-diff=color --minimal out.old out
The only changes in ninja files are in the out/linux_gcc* dirs.  
Bug: b/410777878

build: don't use gold on Linux standalone builds

---

ui/src/core/trace_impl.ts
ui/src/core_plugins/commands/index.ts
ui/src/public/app.ts

This change adds a new command that disposes the current trace and removes it from the global AppImpl object. Mainly for testing.

Add command to close the current trace

---

src/trace_processor/importers/ftrace/ftrace_parser.cc
src/trace_processor/importers/ftrace/ftrace_tokenizer.cc

This reverts commit c9f2646bd3fa0dfabfc8968fc83a712b6e04998a.
With issue fixed in b/407752170, reenable cpm tracepoints.

Revert "thermal: perfetto/ftrace: Disable parsing param_set_value_cpm"

---

Android.bp
BUILD
src/trace_processor/metrics/sql/android/android_lmk.sql
src/trace_processor/metrics/sql/android/android_lmk_reason.sql
src/trace_processor/perfetto_sql/stdlib/android/memory/BUILD.gn
src/trace_processor/perfetto_sql/stdlib/android/memory/lmk.sql
test/trace_processor/diff_tests/stdlib/android/memory.py

stdlib module to support the newer instant events and (eventually) deprecate the trace processor handling during parsing

Introduce android.memory.lmk stdlib module

---

src/protovm/error_handling.h

Add missing "#include <new>" to error_handling.h

protovm: fix missing include

---

include/perfetto/tracing/data_source.h
include/perfetto/tracing/internal/tracing_muxer.h
src/tracing/internal/tracing_muxer_impl.cc
src/tracing/internal/tracing_muxer_impl.h

Instead of copying the fields from DataSourceParams into RegisteredDataSource, let's copy the whole structure.
A future commit will add another field to DataSourceParams that needs to be kept into RegisteredDataSource. This will make that change easier.

tracing_muxer_impl: Use DataSourceParams in RegisteredDataSource

---

persistent_cfg.pbtxt

The flag `persist.debug.perfetto.persistent` no longer exists and we now have `persist.debug.perfetto.persistent_sysui_tracing_for_bugreport` instead to be more descriptive. This PR updates the comments that mention this flag which is no longer used.

Update SysUI persistent tracing flag name in comments

---

ui/src/plugins/dev.perfetto.AndroidLog/logs_panel.ts

In multi-VM traces, it is valuable to differentiate from which machine each Android log is coming from. For this we added a machine id column to the table in the AndroidLog panel. This columns is conditional to there being more than one machine, if not then the log panel behaves the same way as before.
Test: ui/run-unittests
Bug: 406061688

Add machine id column to AndroidLog panel

---

include/perfetto/tracing/track_event_legacy.h

Its last usage was removed in https://crrev.com/c/6197645.
I am also going to send CLs to Chromium & V8 to remove the other remaining usages
(https://source.chromium.org/search?q=TRACE_EVENT_OBJECT_SNAPSHOT_WITH_ID_AND_TIMESTAMP&ss=chromium).

Remove TRACE_EVENT_OBJECT_SNAPSHOT_WITH_ID_AND_TIMESTAMP

---

src/trace_processor/perfetto_sql/stdlib/android/frames/timeline.sql

Choreographer#doFrame and DrawFrame can have frame_id of -1, indicating an invalid vsync id according to Android Open Source. If the trace file contains data with frame_id = -1, it results in Cartesian product when joining the android_frames_chore_do_frame,_frames_draw_frame, and fallback tables in srctrace_processor/perfetto_sql/stdlib/frames/timeline.sql.
For example, there are 100 rows with frame_id =1, the JOIN operation produces 100 100 * 100 = 1,,000 rows, leading to wasm OOM issues.
This commit includes the following changes:
1. Modified _get_frame_table_with_id function to filter out slices with frame_id = -1.
Bug: https://github.com/google/perfetto/issues/1390

Filter out frame_id = -1 in _get_frame_table_with_id 

---

ui/src/core/workspace_manager.ts

- Add 'defaultWorkspaceEditable' feature flag to control workspace editability
- Allow track removal and reordering when flag is enabled
- Maintain default workspace read-only state when flag is disabled
More discussion
https://github.com/google/perfetto/discussions/1343

feat(ui): add feature flag to enable editing in default workspace

---

ui/src/base/vertical_line_helper.ts
ui/src/core/track_manager.ts
ui/src/frontend/viewer_page/track_tree_view.ts
ui/src/plugins/dev.perfetto.CpuSlices/common.ts
ui/src/plugins/dev.perfetto.CpuSlices/cpu_slice_track.ts
ui/src/plugins/dev.perfetto.CpuSlices/index.ts
ui/src/plugins/dev.perfetto.CpuSlices/waker_overlay.ts
ui/src/public/selection.ts
ui/src/public/track.ts

This change adds the following:
- A new overlay rendering subsystem which allows plugisn to render an overlay on top of the timeline (on top of tracks other tracks).
- The CpuSlices plugin uses this new overlay rendering mechanism to to render the waker the waker information over the top of the timeline when CPU slices are selected.
- This moves a lot of the custom waker information from the core into the plugin, tidying up the core a lot.

Add pluginable overlay subsystem & use for waker lines for cpu tracks

---

ui/src/core_plugins/track_utils/index.ts

Now that we have settings, this PR moves the dvorak mode to be a setting instead of a flag.
No effort has been made to migrate the old flag's config to the new setting, so users will have to enable it again in the settings.

Move dvorak mode flag to a setting

---

include/perfetto/ext/base/string_utils.h
src/base/http/http_server.cc
src/base/string_utils.cc
src/base/string_utils_unittest.cc
ui/src/trace_processor/http_rpc_engine.ts

fix firefox with trace_process_shell
issue: https://github.com/google/perfetto/issues/1301

Fix/trace process shell/erorr on firefox

---

ui/src/frontend/ui_main.ts

This operation is actually what most people want when they use 'M' to create an annotation. They don't want to create an annotation at all, they just want to convert a the selected slice to an area selection so that they can perform aggregations over that time range.
'R' is a good choice for this hotkey because:
- You can press it with your left hand while mousing with your right (assuming right handed users using a QWERTY/AZERTY layout).
- It doesn't collide with the WASD key equivalents in DVORAK/AZERTY layout.
- It's one of the letters in the word 'aRea'.

Add "R" hotkey to create area selection from event selection

---

include/perfetto/ext/base/unix_socket.h

This is to fix module build in chromium.

Add a missing include for unix_socket.h

---

src/protovm/test/slab_allocator_unittest.cc

This fixes the build on some windows environments, where apparently there's no std:;aligned_storage (which is also deprecated in C++23).

Avoid std::aligned_storage

---

src/trace_processor/dataframe/type_set.h

bytecode::SortedFilterBase::EstimateCost is constexpr and uses dataframe::TypeSet, which needs to have a constexpr constructor according to MSVC.

Make dataframe::TypeSet constructor constexpr

---

infra/luci/recipes/perfetto.expected/ci_tag.json
infra/luci/recipes/perfetto.py

Since a6ec3cf0d3("perfetto: use Chromium mirror for LUCI (#1183)"), the way tags are described in the checked out repo has changed.
Instead of v50.1, the tags show up as upstream/v50.1
Proof:
* For v49.0, the cipd package was tagged as v49.0 https://chrome-infra-packages.appspot.com/p/perfetto/trace_processor_shell/linux-arm64/+/wqR1jrSJAocyjh6cY-pJIE3QF6wfdTdkfkE2rk-rCYIC
* For v50.1, the cipd package is tagged as upstream/v50.1 https://chrome-infra-packages.appspot.com/p/perfetto/trace_processor_shell/linux-arm64/+/HXtZkPE1_oU74BLM0TFg3RNqojF0u4_A2dwKgxmUddwC
the tag used for cipd comes from `ctx.maybe_git_tag`, so we need to fixed that.
Partially generated via `cd infra/luci && ./recipes.py test train`

luci: Handle tag in the new github repo

---

Android.bp
src/trace_redaction/BUILD.gn
src/trace_redaction/drop_empty_ftrace_events.cc
src/trace_redaction/drop_empty_ftrace_events.h
src/trace_redaction/drop_empty_ftrace_events_unittest.cc
src/trace_redaction/trace_redactor.cc

Some transform primitives, can produce empty ftrace events. Because ftrace events make-up the bulk of a trace, these empty events waste a lot of space. For one sample we saw,
- 11 MB before removing empty ftrace events
-  6 MB after removing empty ftrace events
To avoid every transform from cleaning up after itself, we introduce a transform that looks for and removes empty ftrace events. 
However, this new transform does not fully solve the problem, but rather moves it up one level of abstraction, instead of empty ftrace events, we need to worry about empty ftrace bundles.
Bug: 399223002
Bug: 400076815

Trace Redaction - Remove empty ftrace events

---

src/trace_processor/importers/proto/android_probes_parser.cc
src/trace_processor/importers/proto/android_probes_parser.h

Use a dedicated args tracker for power rails parsing in order to workaround non-linear parsing performance. This should result in significant parse time improvements for traces with O(10 million) power samples and above.
Bug: https://github.com/google/perfetto/issues/1323

tp: use dedicated args tracker for power rails

---

ui/src/plugins/dev.perfetto.AndroidLog/index.ts
ui/src/plugins/dev.perfetto.AndroidLog/logs_panel.ts

In multi-machine traces doing log analysis might be complicated given there could be thousands of logs from each machine in the same log table. To improve the log navigation, we added a multi-select filter which allows the user to select any subset of machines to only view their respective logs.
Test: ui/run-unittests
Bug: 406061688

Add machine id filter to AndroidLog

---

src/shared_lib/test/api_integrationtest.cc
src/tracing/test/api_integrationtest.cc

Coverage for e2b0047c1e67("Fix null dereference in v8 (#1388)"). One of the tests was able to reproduce the bug when run with GCC.

tracing: Test when perfetto is not initialized

---

src/trace_processor/perfetto_sql/stdlib/android/frames/timeline.sql
test/trace_processor/diff_tests/metrics/graphics/android_doframe_depth.py
test/trace_processor/diff_tests/stdlib/android/frames_tests.py

Current depth check limits filtering Choreographer#doFrame slices to be at depth 0 and 1. There are cases where the frame slice can be at level 2(eg. b/413987043). The depth check was kept earlier to eliminate resynced slices. This check is not required as the current table logic eliminates these slices with the integer cast.
Bug: 413987043
Test: tools/diff_test_trace_processor.py --name-filter ".*frames.*" out/linux_clang_debug/trace_processor_shell

Remove depth check for filtering frame slices.

---

test/trace_processor/diff_tests/metrics/graphics/composer_execution.py

Remove the abandoned onMessageRefresh in old Android versions
In Android T and higher, the atrace event of SurfaceFlinger::onMessageRefresh() is indeed deprecated, so the logic of these test codes needs to be adjusted. If the test is only for Android T+, it is recommended to directly delete all onMessageRefresh related Trace events, because the function has been removed from the code base and its Trace events are no longer generated. In addition, the function of onMessageRefresh has been refactored and optimized in Android T, and its core logic has been integrated into the new process of CompositionEngine. It is recommended to replace onMessageRefresh here with the Trace event of the new function (such as CompositionEngine::present()).
Make sure your PR has a …

Replace the deprecated onMessageRefresh with present

---

Android.bp
BUILD
tools/gen_android_bp
tools/gen_bazel

We need this to parse an 'AndroidMessageQueue' proto event in tests.

Export 'android_track_event' proto as a separate target in BUILD and Android.bp.

---

protos/perfetto/trace_summary/v2_metric.proto
src/trace_processor/trace_summary/summary.cc
test/trace_processor/diff_tests/summary/metrics_v2_tests.py
test/trace_processor/diff_tests/summary/simple_slices_metric_v2.out
test/trace_processor/diff_tests/summary/synth_simple_slices.py

Add support for dimension spec in metrics v2
* Explicitly specify the expected type of the dimension in the metrics v2 output
* Accept null for all dimension types
* Continue supporting dimensions without explicit types being specified 
*  Read columns based on spec dimension/metric column names not based on order to 
* Fix bug on wrong output produced in the case different dimension order between the query and the spec
* Fix bug on wrong metric value emitted, incase of the metric column is not the last
* Add test for simple_slices in metrics v2
Bug: 415966029
Test: `tools/ninja -C out/linux_clang_debug  && tools/diff_test_trace_processor.py  out/linux_clang_debug/trace_processor_shell --name-filter=".*SummaryMetricsV2.*"`

Add support for dimension spec in metrics v2

---

ui/src/plugins/dev.perfetto.CriticalPath/index.ts
ui/src/public/selection.ts

This patch removes the `utid` field from the core selection object.
The only component that uses this field is the critical path plugin. This has been changed to look up the utid on demand from the track tags and/or the dataset.
This is part of the movement to remove anything thread related from the core.

Remove `utid` field from core selection object

---

ui/src/core/selection_manager.ts
ui/src/plugins/dev.perfetto.HeapProfile/heap_profile_track.ts
ui/src/plugins/dev.perfetto.HeapProfile/index.ts

https://buganizer.corp.google.com/issues/416190258
When loading a trace with heap profile tracks, we automatically select the earliest heap profile sample on trace load.
We currently assume that this event has id = 0, but this is not necessarily the case.
This change refactors the queries in the heap profile plugin to make things a lot clearer, as it was getting out of control, and also fixes the bug so that it works out the necessary event id properly.
This change also refactors the selection logic in SelectionManager a little to make the error message clearer and to ease debugging in the future.

Fix crash in heap profile auto-selection at trace load time

---

src/trace_processor/importers/etw/etw_parser.cc

Chrome ETW translator erases thread id for processes that aren't chrome, for privacy/security concerns.
This updates trace processor to avoid interpreting this as idle, which gets explicitly thread_id = 0.
This uses -1 to represent erased thread id.

[ETW] Fix erased thread_ids

---

ui/src/plugins/dev.perfetto.Ftrace/ftrace_track.ts

This allows dataset search to work (or at least, not crash) when encountering an event on the ftrace track.

Implement getSelectionDetails() in ftrace track

---

src/trace_processor/perfetto_sql/stdlib/viz/summary/track_event.sql

Optimize the min_ts_per_track query for tracks with large numbers of samples by limiting the results of the query to only contain timestamps for track event tracks and not power rail tracks.
This query change is essentially @LalitMaganti's suggestion from https://github.com/google/perfetto/issues/1323 with some minor formatting fixes.
Testing:
- Validate example Android and Chrome trace open (there is a very minor ~20 ms perf penalty from on loading these traces)
- Validate that power rail trace from https://github.com/google/perfetto/issues/1323 now shows negligible time spent loading plugins (now much less than 1 sec, previously ~10 sec)
Bug: https://github.com/google/perfetto/issues/1323

tp: optimize min_ts_per_track query

---

src/trace_processor/importers/proto/winscope/shell_transitions_parser.cc
test/trace_processor/diff_tests/parser/android/shell_transitions.textproto
test/trace_processor/diff_tests/parser/android/tests_shell_transitions.py
test/trace_processor/diff_tests/syntax/table_tests.py

A previous bug prevented dispatch time from being added to the table as a timestamp if it was present in a first message, due to the row only existing after being added to the args table.
Bug: 411363817
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter="ShellTransitions"

Add dispatch time as ts even if present in first message.

---

infra/ci/sandbox/Dockerfile

* still has gcc-8 allowing us to test old versions
* emscripten is blocked on Python3.8 being available. Getting it on
Debian buster is too hard. It's not even in backports
* 20.04 is still in official support window which Buster is EOL

ci: migrate dockerfile to Ubuntu 20.04

---

ui/src/base/time.ts
ui/src/components/widgets/timestamp_format_menu.ts
ui/src/core/fake_trace_impl.ts
ui/src/core/load_trace.ts
ui/src/frontend/ui_main.ts
ui/src/frontend/viewer_page/time_axis_panel.ts
ui/src/public/trace_info.ts

The PR adds a printout of the timezone in various places in the UI:
- In the top-left of the timeline next to the timestamp offset:
- In the timestamp selection menus

Print timezone on the UI

---

src/trace_processor/importers/proto/winscope/surfaceflinger_transactions_parser.cc
test/trace_processor/diff_tests/parser/android/tests_surfaceflinger_transactions.py

Transaction flags_id was not being set for changed/added displays.
Bug: 411363817
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter="SurfaceFlingerTransactions"

Add transaction to table only after flags decoded.

---

protos/perfetto/config/chrome/scenario_config.proto

This PR adds a description string field to ScenarioConfig, which will be displayed in Chrome internal UI.

[chrome] Add scenario description string

---

python/tools/check_imports.py

Allow engine/* to import from gen/trace_processor_memory*.

Fix import rules

---

ui/src/plugins/dev.perfetto.QueryPage/index.ts

Add a new 'mini' query page tab which displays a mini version of the query page in a tab on the viewer page. This is useful for quickly modifying queries and seeing the results, while being able to compare results against the timeline.
This tab is behind a flag initially as it's very rough and still needs some polish.
Going forward, this tab should sync with the query page itself, taking the place of the 'Standalone Query' tab that's created on the viewer page whenever a query is run on the query page.

Add "mini" query page tab

---

ui/src/plugins/dev.perfetto.ThreadState/index.ts
ui/src/plugins/dev.perfetto.ThreadState/thread_state_track.ts

This change makes it so that the thread state tracks generate the slice titles using the stdlib function `sched_state_io_to_human_readable_string` in SQL rather than doing the conversion in JavaScript.

Convert `thread_state.state` to a human readable value in SQL rather than JS

---

Android.bp
BUILD
src/trace_processor/perfetto_sql/stdlib/android/BUILD.gn
src/trace_processor/perfetto_sql/stdlib/android/entity_state_residency.sql
test/trace_processor/diff_tests/parser/power/tests_entity_state_residency.py

Add the entity_states_residency data to sql standard library so that it can be more easily queried by plugins later.
this implementation was inspired by the existing
android_power_rails_counters API and implementation, but deliberately diverges in a few ways:
- It does not use counter_leading_intervals, since merging counter intervals can negatively impact average time in state computations.
- It omits the delta value since it can be confusing and potentially result in bugs since it references the previous sample unlike every thing else in the API which gives data relative to the next sample. See https://github.com/google/perfetto/pull/1455 for context.
Bug: https://github.com/google/perfetto/issues/1321

add entity_state_residency to sql standard library

---

gn/standalone/toolchain/BUILD.gn
gn/standalone/wasm.gni
src/trace_processor/BUILD.gn
ui/build.js
ui/config/rollup.config.js
ui/src/engine/index.ts
ui/src/engine/trace_processor_32_stub.ts
ui/src/engine/wasm_bridge.ts

- Reduce duplication in .gni files
- Make 64-bit detection synchronous. The async adds extra complexity that can be avoided.
- Change the way 64-bit-only is passed. I am not a an of the "async import" as that
IMHO creates unnecessary risks and makes the code even more complicate due to
an unnecessary async. Instad use a stub import + rollup to redirect to the real import.
- Rollback some of the changes to engine.ts. I don't like the extra layers introduced by
#1458. I think the previous model where wasm_bridge.ts does everything is cleaner.
- Fix a bug which #1458 accidentally re-introduced on wasm32, where addresses that are
between 2GB and 4GB accidentally become negative offsets.
I tested it both on Chrome (which supports wasm64) and an older Firefox (which doesn't)

Improve wasm64 support

---

src/trace_processor/perfetto_sql/stdlib/android/memory/heap_graph/helpers.sql
ui/src/components/query_flamegraph.ts

This is useful e.g. to filter by root type or by heap type (e.g. ss:
HEAP_TYPE_APP to avoid looking at boot / zygote classes for a heap dump)
Bug: 417266471

Flame graph filtering by unaggregated properties 

---

src/trace_processor/rpc/rpc.cc
src/trace_processor/trace_processor_storage_impl.cc
src/trace_processor/trace_processor_storage_impl.h

Preloaded instances are passed being in an EOF state (i.e. with trace
already full loaded). Not having this leads to TP ending up in an
inconsistent state.

tp: fix invalid state on preloaded TP

---

src/trace_processor/importers/archive/tar_trace_reader.cc

Add a size validation to ensure file sizes do not exceed the maximum value of `size_t`,
preventing overflows and incorrect calculations in 32-bit environments.

Fix memory corruption for TAR files >4GB on browser

---

src/tracing/test/api_integrationtest.cc

This adds TrackEvent tests in preparation for API changes in
https://github.com/google/perfetto/pull/1432
Bug: chromium:260418655

[TrackEvent] Add tests for upcoming API changes

---

test/cts/heapprofd_test_cts.cc
test/cts/heapprofd_test_helper.cc
test/cts/heapprofd_test_helper.h

These tests are relying on the fact that callstacks can provide information about which function called malloc/free.
This is not the case for apps running with native_bridge. For these there exists 2 different stacks (native one - visible to perfetto) and another one for emulated architecture (to access which perfetto needs to read and unwind second, - guest stack).
The result is that as of now all native callstacks for memory allocations originated for emulated apps look the same and get aggregated together. And this is why test does not pass.
Bug: 411111586
Test: run heapprofd tests on Android Emulator under native bridge
Change-Id: I24499cd22095e3c0002bc426ff4c9d64dfb9b8e6
(cherry picked from commit ada6248a1f195ed278e2956602f2f161d1baed6c)

Disable some heapprofd cts tests for native bridge [cherry-pick]

---

.github/workflows/require-two-reviewers-for-fork-prs.yml

I suspect this is due to the fact that the action is not re-ran when the 2nd reviewer approves.
Adding a speculative fix for it plus more debugging

Github Action: add debug output to 2-reviewers check

---

ui/src/assets/record.scss
ui/src/plugins/dev.perfetto.RecordTraceV2/pages/probe_renderer.ts

Allows to add ``` code blocks ``` in the probe description.
Needed for https://github.com/google/perfetto/pull/1510

UI: add support for triple-backtick code blocks

---

ui/src/plugins/dev.perfetto.AndroidLongBatteryTracing/index.ts

Since they can take a while to calculate we hide them behind a command.
To make it more obvious when the command has finished, we open the first group by default.
While we're here, clean up a little bit: import correct objects for iterator types, and check for google3 with a fallthrough only once instead of repeatedly.
Bug: http://b/417417058

Make Day Explorer blames available in the Perfetto UI.

---

protos/perfetto/trace/android/view/insetssource.proto

This is necessary to let CTS support relative insets. Also the information can be used for debugging.
Test: CTS: SplashscreenTests
Bug: 277292497
Change-Id: I94b15644ef1efa58d3b8d5c851bfecb569e7b8ad

Dump attached insets in InsetsSource

---

.github/workflows/require-two-reviewers-for-fork-prs.yml

I just realized that the latest changes can be confusing for googlers.
For them the check will never trigger if they don't upload a new
patchset or use auto-merge.
Add a trigger on creation, which will always pass for googlers.

CI: add 'opened' event to two reviewer check

---

ui/src/plugins/dev.perfetto.RecordTraceV2/config/config_interfaces.ts
ui/src/plugins/dev.perfetto.RecordTraceV2/pages/gpu.ts

These can be enabled for supported devices via the following adb commands
```shell
adb root
adb shell setprop debug.graphics.gpu.profiler.perfetto 1 
adb shell gpu_counter_producer
adb shell start gpu_probe
```
More info about profiling can be found here go/gpu-profiling
Bug: 417602907

Add data sources for GPU tracing

---

src/trace_processor/perfetto_sql/stdlib/android/kernel_wakelocks.sql

We accidentally had an extra `WHERE` clause that meant we were only counting awake time towards `dur`. Fix that, and expose `awake_dur` in case anyone actually wants that.

Fix duration in android_kernel_wakelocks table.

---

ui/src/plugins/dev.perfetto.SqlModules/index.ts

Fixes: https://buganizer.corp.google.com/issues/413722658
We have guard rails in place to stop traces from loading simultaneously, but these guard rails are only good if the plugins doo all their loading within their onTraceLoad() function. The SqlModules plugin starts a fetch from the server and immediately returns, indicating to the core that it's done loading while the fetch completes some time later.
When two traces are loaded in quick succession, we can end up with two loadJson() functions running concurrently. When they resolve they both try to add the same command to the command registry resulting in an error as seen in the bug report.
This patch fixes the immediate problem by awaiting the fetch within the plugin's onTraceLoad() function.

Await loadJson() in dev.perfetto.SqlModules plugin

---

src/traceconv/main.cc

Currently, traceconv fails when trying to specify either of these arguments when using `java_heap_profile`, but this subcommand support them. Also updated the error message to mention 'hprof' format too.
Tested by running: `traceconv java_heap_profile --timestamps 14335729096436 --pid 16437` and checked that it output a valid profile.

[traceconv] Allow passing pid/timestamps to java_heap_profile format

---

ui/src/frontend/viewer_page/resolution.ts
ui/src/frontend/viewer_page/search_overview_track.ts
ui/src/frontend/viewer_page/track_view.ts

The `calculateResolution` function is used to work out the horizontal resolution at which data should be loaded for a given timespan and horizontal width (e.g. of a canvas) in px. If either of these values are 0 or negative, this function currently returns 1n. This causes issues as loading data at a resolution of 1 is rarely what you actually want to do in this instance, and it usually produces very slow queries which can cause the UI to hang and generally become unresponsive.
This patch makes `calculateResolution` return a `Result<bigint>` type instead, and returns an error value when the inputs are 0 or negative. Using a `Result<T>` type rather than throwing an error forces callers to handle the error case at the callsite so it cannot be ignored. In this case, if resolution cannot be …

Fix UI hang when loading data for 0 or negative canvas sizes

---

src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql

Fix the type for the id column in android_power_rails_counters as the use of a long type was mentioned to be a bug in https://github.com/google/perfetto/pull/1457#discussion_r2085086053

fix android_power_rails_counters id column type

---

ui/src/plugins/dev.perfetto.EntityStateResidency/entity_state_residency_selection_aggregator.ts
ui/src/plugins/dev.perfetto.EntityStateResidency/index.ts

Add a plugin to handle entity state residency. This plugin aims to present existing aggregation data in a more user-friendly manner, as well a remove aggregations that do not make sense. This is similar in concept to https://github.com/google/perfetto/pull/1211
This commit DOES NOT aim to fix any existing errors in computation like is mentioned in https://github.com/google/perfetto/issues/1478 and instead just aims to focus on better labeling for existing data
BUG: https://github.com/google/perfetto/issues/1321

Add plugin to handle entity state residency aggregation

---

ui/src/frontend/viewer_page/resolution.ts
ui/src/frontend/viewer_page/search_overview_track.ts
ui/src/frontend/viewer_page/track_view.ts

The `calculateResolution` function is used to work out the horizontal resolution at which data should be loaded for a given timespan and horizontal width (e.g. of a canvas) in px. If either of these values are 0 or negative, this function currently returns 1n. This causes issues as loading data at a resolution of 1 is rarely what you actually want to do in this instance, and it usually produces very slow queries which can cause the UI to hang and generally become unresponsive.
This patch makes `calculateResolution` return a `Result<bigint>` type instead, and returns an error value when the inputs are 0 or negative. Using a `Result<T>` type rather than throwing an error forces callers to handle the error case at the callsite so it cannot be ignored. In this case, if resolution cannot be …

Cherrypick: Fix UI hang when loading data for 0 or negative canvas sizes (#1563)

---

src/trace_processor/perfetto_sql/stdlib/android/kernel_wakelocks.sql

https://github.com/google/perfetto/pull/1554 was broken due to last minute cleanup. ts gets renamed in the query and the GROUP BY was applied to the wrong one (pre rename not post rename).
Bug: http://b/418182182

Fix android_kernel_wakelocks.

---

infra/ci/Makefile
infra/ci/config.py
infra/ci/worker/gce-startup-script.sh
infra/ci/worker/sandbox_runner.py

The current design (before this CL) uses the MIG autoscaler to scale up and down.
That creates the problem that the autoscaler can shutdown a VM that has sandboxes
running, if they pick up the job late. This CL changes it to a new strategy where:
- The autoscaler only scales up
- Each GCE VM self-shutdowns after all sandbozes are idle for 90 mins.
This should reduce the possible race significantly and avoid interrupted jobs.
Bug: b/417658206

CI: change downscaling strategy to avoid interruptions

---

.github/workflows/analyze.yml
.github/workflows/pr-branch-check.yml
.github/workflows/require-two-reviewers-for-fork-prs.yml

My theory is that we can make the CI more responsive by moving
the small jobs that don't require our sandbox on GitHub's pool.
This is particularly important for analyze.yml, which is an
input for the autoscale: if that doesn't run, the autoscaler
won't scale up much as it sees only one job (it will only scale
up after analyze.yml has run). This should reduce queue times
when the CI is idle.

ci: run small jobs on GitHub's pool rather than ours

---

.github/workflows/analyze.yml

This is to allow dynamically skipping jobs but also ensuring
that all non-skipped jobs have succeeded.

ci: add gate job to join nested workflows

---

.github/workflows/analyze.yml
tools/run_presubmit

Problem: A...B means git diff $(git merge-base A B) B
1) This is not what we want
2) This breaks due to shallow checkouts in some cases
3) When 2 happens, it creates false-positives in the trivial/skip detection
(e.g. https://screenshot.googleplex.com/AnTCRA629ejZxn3)

ci: use git diff A B not A...B for change detection

---

.github/workflows/analyze.yml
.github/workflows/repo-checks.yml

Mask out the tests that depend on diffing the CL against the merge base.
They make no sense in post-submit, as we want to check the state of the repo as-is.

ci: fix postsubmit

---

ui/src/core_plugins/track_utils/index.ts
ui/src/frontend/viewer_page/track_view.ts

This patch adds the following:
- Consistently apply the little arrow to join path elements when printing full track path names in the UI, including in the 'Find track by name' command dropdown (see attached image).
- Add 'Mod+P' hotkey to 'Find track by name', which is analogous to the 'Find file' hotkey in VSCode.

Improve 'Find track by name' command UX

---

ui/src/plugins/dev.perfetto.RecordTraceV2/pages/gpu.ts

`gpu_probe` and `gpu_counter_producer` do the exact same thing: starting the GPU counter Perfetto data source. However, `gpu_probe` requires root, whereas `gpu_counter_producer` does not. Neither of them is needed for render slices or the extra ftrace events.

Fix the instructions for the recently added GPU probes.

---

protos/perfetto/trace/android/view/displayinfo.proto

This can be used to distinguish between the main display and the virtual display.
This CL is a port of ag/28185252 into external/perfetto.
Flag: NONE dumping new field to proto
Bug: 351162994
Test: adb shell dumpsys window --proto
Change-Id: Ic731e2143fe8c4ba57c48cced141cbb910fefe2e (cherry picked from commit d95cff731af8a511a0be86f0080310cbe8542e6a)

Dump type from DisplayInfo

---

src/kernel_utils/kernel_wakelock_errors.h
src/trace_processor/importers/proto/android_kernel_wakelocks_module.cc
src/trace_processor/storage/stats.h
src/traced/probes/android_kernel_wakelocks/android_kernel_wakelocks_data_source.cc
src/traced/probes/android_kernel_wakelocks/android_kernel_wakelocks_data_source.h

We see very high values occasionally from SuspendControlService. If we do, ignore them and set an error flag.
Bug: http://b/404239369

Kernel wakelocks: be even more defensive.

---

Android.bp
BUILD
src/android_sdk/java/test/dev/perfetto/sdk/test/PerfettoTraceTest.java
src/android_sdk/jni/BUILD.gn

In framework, we usually don't add '_lib' suffix for the native libs, so rename the perfetto native lib binary.
Tested:
```
tools/bazel test //:src_android_sdk_java_test_perfetto_trace_instrumentation_test
```

Android Java SDK: rename 'perfetto_jni_lib' to 'perfetto_jni'.

---

ui/src/components/tracks/base_slice_track.ts
ui/src/components/tracks/dataset_slice_track.ts
ui/src/plugins/dev.perfetto.AndroidDmabuf/index.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/index.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/trace_processor_slice_track.ts
ui/src/plugins/dev.perfetto.TrackEvent/index.ts
ui/src/plugins/org.kernel.LinuxKernelSubsystems/index.ts
ui/src/plugins/org.kernel.SuspendResumeLatency/index.ts

Async track depths are calculated using `experimental_slice_layout` which, when passed verbatim to BaseSliceTrack, can be very slow when cross joining on the result of the mipmap table. Currently we avoid this by allowing the cross join to operate directly on the slice table, because depths are not required anyway, but this is a hack and makes the code hard to reason about and leaves rough edges for users of DatasetSliceTrack.
This patch makes it so that the track depths are calculated up front when an async slice track is created. This is much more efficient that trying to cross join on it even once, and only happens one on startup, leaving the cross joins to be fast.
This also means we can remove the getSqlJoinSource() hack in BaseSliceTrack, which has been removed in this CL.

Cache async track depths before at creation time.

---

ui/src/components/colorizer.ts
ui/src/components/tracks/base_slice_track.ts
ui/src/components/tracks/dataset_slice_track.ts
ui/src/plugins/dev.perfetto.Sched/thread_state_track.ts

This allows tracks to separate slices onto different layers where each layer is mipmapped independently.
Very short but important slices which would normally be swamped by any longer but less important slices if they were on the same layer. By moving them onto separate layers, we can mipmap the separately making sure the more important slices show up on the track.
This patch also modifies the 'thread slice' track to take advantage of the layer functionality to ensure non-idle slices are displayed above idle ones.

Add layer support in DatasetSliceTrack & BaseSliceTrack

---

src/trace_processor/perfetto_sql/intrinsics/functions/replace_numbers_function.h

Include <stdint.h> is for int64_t.

Add a missing include for replace_numbers_function.h

---

ui/src/components/tracks/base_counter_track.ts

It can be reproduced with the following txt trace:
```
HwBinder:640_1-721   (  640) [000] ...1 6824711.854000: tracing_mark_write: I|640|event
HwBinder:640_1-721   (  640) [000] ...1 6824711.854890: tracing_mark_write: C|640|counter|1
```
Bug: https://b.corp.google.com/issues/419524104

Fix a ui track crash when a counter is the last event

---

examples/shared_lib/example_shlib_track_event.c
include/perfetto/public/abi/track_event_hl_abi.h
include/perfetto/public/te_macros.h
src/shared_lib/test/api_integrationtest.cc
src/shared_lib/track_event.cc

This allows, emitting a PERFETTO_TE() event into a hierachy of multiple nested tracks.
For example
```
PERFETTO_TE(cat, PERFETTO_TE_INSTANT("event"),
PERFETTO_TE_NESTED_TRACKS(
PERFETTO_TE_NESTED_TRACK_PROCESS(),
PERFETTO_TE_NESTED_TRACK_NAMED("parent", 2),
PERFETTO_TE_NESTED_TRACK_NAMED("child", 2)
));
```
emits "event" in the hierarchy of tracks:
```
Current process
|
└──"parent"
|
└──"child"
```
Bug: https://b.corp.google.com/issues/415332664

shared_lib: Add PERFETTO_TE_NESTED_TRACKS() param

---

ui/src/components/aggregation_panel.ts
ui/src/components/colorizer.ts
ui/src/components/selection_aggregation_manager.ts
ui/src/plugins/dev.perfetto.EntityStateResidency/entity_state_residency_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Frames/frame_selection_aggregator.ts
ui/src/plugins/dev.perfetto.PowerAggregations/power_counter_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/common.ts
ui/src/plugins/dev.perfetto.Sched/cpu_slice_by_process_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/cpu_slice_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/thread_state_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/thread_state_track.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/counter_selection_aggregator.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/slice_selection_aggregator.ts
ui/src/plugins/org.kernel.Wattson/aggregation_panel.ts
ui/src/plugins/org.kernel.Wattson/estimate_aggregator.ts
ui/src/plugins/org.kernel.Wattson/package_aggregator.ts
ui/src/plugins/org.kernel.Wattson/process_aggregator.ts
ui/src/plugins/org.kernel.Wattson/thread_aggregator.ts
ui/src/public/aggregation.ts
ui/src/public/selection.ts

In the past, thread state aggregation tabs used to have a little bar chart at the top of the panel showing the proportions of thread states within the selected area. This was lost after a refactor.
The way this used to work was very hacky - there was a special case for the thread state tab that the core knew about.
This patch changes this special case to a more generic 'bar chart' interface, where aggregators can specify bar chart data, which the thread state aggregator makes use of to bring its bar chart back to life.
Removing this special case also means that we can remove the hard dependency on thread state structures and colors from the core, allowing us to remove anything thread state related into the 'Sched' plugin.

Add bar chart support to the aggregation adapater

---

buildtools/.gitignore

This file should have been added to .gitignore in 2024
when the optional install-build-dep entry was introduced.
I think we never noticed until now because bigtrace was not used in the CI.
This is now causing some CI errors.

add buildtools/cpp-httplib to gitignore

---

src/android_sdk/java/main/dev/perfetto/sdk/PerfettoTrackEventBuilder.java

When building perfetto event, we need to keep references to the 'PerfettoPointer' objects that are used by that event. Otherwise, the GC can collect them, and the 'native_delete' function will be called while the native part of the object is still in use.
In this CL we fix the way we keep such references: we pass the same 'ArrayList' for all the child 'PerfettoTrackEventBuilder's, the same way we pass 'ObjectsPool's, 'ObjectsCache's and other caches.
Tested:
```
tools/bazel test //:src_android_sdk_java_test_perfetto_trace_instrumentation_test
```

Android Java SDK: use the same list to keep native objects in the root event builder.

---

.github/workflows/repo-checks.yml

Poor YAML escaping was causing the --skip-formatters argument to be ignored

Fix run_presubmit in repo_checks

---

Android.bp
BUILD
src/trace_processor/perfetto_sql/stdlib/wattson/BUILD.gn
src/trace_processor/perfetto_sql/stdlib/wattson/cpu/estimates.sql
src/trace_processor/perfetto_sql/stdlib/wattson/estimates.sql
src/trace_processor/perfetto_sql/stdlib/wattson/gpu/estimates.sql
test/trace_processor/diff_tests/metrics/android/wattson_atrace_apps_threads.out
test/trace_processor/diff_tests/stdlib/wattson/tests.py
ui/src/plugins/org.kernel.Wattson/index.ts

Create a root estimates.sql that has the power estimates for all Wattson subsystems (e.g. CPU, GPU, etc.). This means moving the original CPU estimates into its own separate directory.
This change causes some inconsequential rounding errors, due to more slices being split up when the GPU estimates are SPAN_JOIN-ed. The slices with smaller time intervals may lose some precision when computing average power.
Bug: 419369871

stdlib: Combine all Wattson subsystem estimates

---

src/trace_processor/storage/stats.h

All these errors are caused by or effectively lead to data loss in the trace tables and should be reported as such instead of just info.

Update Winscope stats message type

---

Android.bp
BUILD
CHANGELOG
src/trace_processor/perfetto_sql/stdlib/viz/BUILD.gn
src/trace_processor/perfetto_sql/stdlib/viz/aggregation.sql
ui/src/base/time.ts
ui/src/components/selection_aggregation_manager.ts
ui/src/plugins/dev.perfetto.Frames/frame_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/cpu_slice_by_process_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/cpu_slice_selection_aggregator.ts
ui/src/plugins/dev.perfetto.Sched/thread_state_selection_aggregator.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/slice_selection_aggregator.ts
ui/src/public/selection.ts

Use interval intersect to intersect slices by the exact area selection range when doing aggregations.
Any panels that use the area selection aggregator adapter (`createAggregationToTabAdaptor()`) will now be passed the pre-intersected dataset if the selected datasets implement a ts, dur and id columns.

Use interval intersect to slice slices to the exact range of the area selection when performing aggregations

---

ui/src/components/details/args.ts
ui/src/components/details/slice_args.ts
ui/src/components/details/thread_slice_details_tab.ts
ui/src/components/sql_utils/args.ts
ui/src/components/tracks/debug_slice_track_details_panel.ts
ui/src/components/widgets/sql/details/details.ts
ui/src/plugins/dev.perfetto.Ftrace/ftrace_details_panel.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/counter_details_panel.ts
ui/src/plugins/org.chromium.ChromeScrollJank/event_latency_details_panel.ts

The options "Show slices with same arg value" and "Visualize argument" don't apply to ftrace/counter tracks, yet these options were being supplied by the generic renderArguments() function, which was being used for both of these.
This patch maked renderArguments() much more generic, allowing extra menu items to be injected in from the caller via a callback. For convenience, another helper function renderSliceArguments() has been created which called renderArguments() with the extra context menu items, and this is used everywhere where slice arguments are actually required whereas renderArguments() is used for ftrace and counter details panels.

Fix bug where ftrace and counter details panel args has context menu items relevant only to slice table.

---

python/perfetto/trace_processor/api.py
python/perfetto/trace_processor/http.py
python/perfetto/trace_processor/protos.py
python/test/api_integrationtest.py

Extend tp python API to also support bytes (proto) alongside textproto

tp: py_api: Provide TraceSummarySpec as bytes

---

src/trace_redaction/filter_sched_waking_events_integrationtest.cc
src/trace_redaction/filter_task_rename_integrationtest.cc
src/trace_redaction/process_thread_timeline_integrationtest.cc
src/trace_redaction/prune_package_list_integrationtest.cc
src/trace_redaction/redact_process_trees_integrationtest.cc
src/trace_redaction/redact_sched_events_integrationtest.cc
src/trace_redaction/scrub_process_stats_integrationtest.cc
src/trace_redaction/trace_redaction_integration_fixture.h

Many integration tests used the same package names. Each test would declare the same package name/uid. This CL moves the name and uid into the text fixture.

Trace Redaction - Share common package name in tests

---

ui/package.json
ui/pnpm-lock.yaml

This pulls in the latest tar-fs version 3.0.5 -> 3.0.9 which fixes https://github.com/google/perfetto/security/dependabot/147

Bump puppeteer version (and in turn tar-fs version) to patch security issue

---

src/traced/probes/ftrace/ftrace_config_muxer.cc

In case preserve_ftrace_buffer is set on Linux and the user has not
changed the clock to boot manually, the default clock will be "local".
But we were not running the code which reads the clock and snapshots the
value into the trace for clock sync.
Fix this by changing muxer to actually read and set the clock
unconditionally.
Fixes: https://github.com/google/perfetto/issues/1686

probes: don't assume boot clock when preserve_ftrace_buffer is set

---

protos/perfetto/perfetto_sql/structured_query.proto
python/generators/diff_tests/runner.py
src/trace_processor/perfetto_sql/generator/BUILD.gn
src/trace_processor/perfetto_sql/generator/structured_query_generator.cc
src/trace_processor/perfetto_sql/generator/structured_query_generator_unittest.cc
src/trace_processor/trace_summary/summary.cc
test/trace_processor/diff_tests/summary/metrics_v2_tests.py

Before we had to have preamble to state what queries were needed before executing the statement from the `sql`  field. Now we tokenize the `sql` field into statements and push all except the last one into the `preamble` (and validate that they don't produce any results) and push only the last one into the final query.

tp: StructuredQuery.sql supports multi select SQL field

---

src/trace_processor/dataframe/impl/bytecode_interpreter.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc

"Always true" constraints were incorrectly being set to the empty range.
Correct this.

tp: fix lowerbound and upperbound on id columns

---

.github/workflows/pr-include-git-origin-rev-id.yml

The original condition was incorrect because it assumed a pull request **to** `dev/copybara/chromium_tmp`. Instead, we want to run the workflow for pull requests **from** `dev/copybara/chromium_tmp` to `main`.

Update conditions for GitOrigin-RevId workflow

---

ui/src/components/details/process_details_tab.ts
ui/src/components/details/thread_details_tab.ts
ui/src/components/tracks/breakdown_tracks.ts
ui/src/components/tracks/dataset_slice_track.ts
ui/src/components/tracks/debug_slice_track_details_panel.ts
ui/src/components/widgets/sql/details/details.ts
ui/src/components/widgets/sql/pivot_table/aggregations.ts
ui/src/components/widgets/sql/pivot_table/pivot_tree_node.ts
ui/src/components/widgets/sql/table/filters.ts
ui/src/components/widgets/sql/table/table.ts
ui/src/core/dataset_search.ts
ui/src/plugins/org.chromium.ChromeCriticalUserInteractions/generic_slice_details_tab.ts
ui/src/plugins/org.chromium.ChromeCriticalUserInteractions/page_load_details_panel.ts
ui/src/plugins/org.chromium.ChromeTasks/details.ts
ui/src/trace_processor/dataset.ts
ui/src/trace_processor/query_result.ts
ui/src/trace_processor/sql_utils.ts

- Remove `ColumnType` type - an alias of `SqlValue` - just use `SqlValue` instead.
- Replace `import d = DetailsSchema;` with `import {DetailsSchema as d} from ...`.
- Remove `export {SqlValue};` in the middle of `sql_utils.ts` which was being used in various files.

Fix some questionable TypeScript import gymnastics

---

.github/workflows/repo-checks.yml

This is to ensure that the presubmit script has access to the message of the commit under test. This should hopefully fix #1777.

Increase fetch-depth in repo-checks

---

src/trace_processor/dataframe/adhoc_dataframe_builder.h
src/trace_processor/dataframe/runtime_dataframe_builder_unittest.cc

Doing a hashset add on every call was just too bad in terms of
performance. I tried using flathashmap and even wrote a custom optimized
hashset implementation and nothing worked.
In practice, the main case we care about duplicates is to build the
special side data structure for ids. Because of this, switch to using a
bitvector based implementation which is much more efficient.
On a represenative query, this takes the time taken to build the table
from 2.1s to 1.3s with the duplicate checking cost being ~zero

tp: reduce performance cost of duplicate checking

---

src/trace_processor/dataframe/adhoc_dataframe_builder.h
src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/runtime_dataframe_builder_unittest.cc

There's no point sorting if there's only a single order by on a column
which is already sorted

tp: skip sorting when single sort constraint is on ordered column

---

protos/perfetto/trace/generic_kernel/generic_task_state.proto
protos/perfetto/trace/perfetto_trace.proto
src/trace_processor/importers/generic_kernel/generic_kernel_parser.cc
test/trace_processor/diff_tests/parser/generic_kernel/tests.py

When a TID's last state event was TASK_STATE_RUNNING the next event for that TID cannot be running. This indicates data loss in the kernel.
Bug: 424815014

Add error stats for consecutive running state events for same TID

---

src/trace_processor/storage/stats.h

These are happening too regularly in traces currently and causing too much data loss.
Bug: 425721078

Downgrade ProtoLog processing errors to info

---

include/perfetto/tracing/track.h
src/tracing/test/api_integrationtest.cc

It needs to be a forwarding reference.

tracing: Fix NamedTrack::ThreadScoped

---

include/perfetto/tracing/event_context.h

Chrome has a few use case to conditionally emit dynamic name in TRACE_EVENT macro.
This PR exposes ShouldFilterDynamicEventNames() similar to ShouldFilterDebugAnnotations().
Drive-by: Remove filter_debug_annotations member that was needed because client API migration.

Expose EventContext::ShouldFilterDynamicEventNames

---

src/trace_processor/dataframe/impl/bytecode_interpreter_impl.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc

Ensures we don't get caught in a O(n) scan in a O(logn) codepath

tp: bail out of linear scan of elements after 16 tries

---

include/perfetto/tracing/event_context.h
src/tracing/event_context.cc
src/tracing/internal/track_event_internal.cc

It was used temporarily in https://r.android.com/2864782 and it could have been removed since https://r.android.com/2714981.

Remove TraceWriter from EventContext

---

BUILD
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/protolog_message_decoder.cc
src/trace_processor/importers/proto/winscope/protolog_message_decoder.h
src/trace_processor/importers/proto/winscope/protolog_parser.cc
src/trace_processor/importers/proto/winscope/protolog_parser.h
src/trace_processor/importers/proto/winscope/shell_transitions_parser.cc
src/trace_processor/importers/proto/winscope/shell_transitions_parser.h
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.cc
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.h
src/trace_processor/importers/proto/winscope/winscope_context.h
src/trace_processor/importers/proto/winscope/winscope_module.cc
src/trace_processor/importers/proto/winscope/winscope_module.h
src/trace_processor/types/trace_processor_context.h

For pointers to winscope-specific trackers that were previously in TraceProcessorContext.
In a separate WinscopeContext class to prevent circular dependencies with WinscopeModule and the constituent parsers.
Bug: 411363817

Introduce winscope context.

---

src/trace_processor/util/debug_annotation_parser.cc
src/trace_processor/util/debug_annotation_parser.h

Refactored the `ParseNestedValueArgs` function in `DebugAnnotationParser`
to be iterative instead of recursive. This avoids stack overflow issues
with deeply nested annotations.

tp: Make DebugAnnotationParser iterative

---

src/trace_processor/dataframe/impl/flex_vector.h
src/trace_processor/dataframe/impl/flex_vector_unittest.cc
src/trace_processor/dataframe/impl/slab.h
src/trace_processor/dataframe/impl/slab_unittest.cc

2x was causing very high memory use when parsing large heap dumps. Use
1.5x instead which is what also folly's vector uses to be a bit more
reasonable.
Also remove a bunch of confusing code where alignment and capacity
multiples were mixed up. We were not actually using custom alignment
capability in prod so remove it and simplify.

tp: change growth factor of flexvector to 1.5x

---

Android.bp
BUILD
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/protolog_message_decoder.cc
src/trace_processor/importers/proto/winscope/protolog_message_decoder.h
src/trace_processor/importers/proto/winscope/protolog_parser.cc
src/trace_processor/importers/proto/winscope/protolog_parser.h
src/trace_processor/importers/proto/winscope/shell_transitions_parser.cc
src/trace_processor/importers/proto/winscope/shell_transitions_parser.h
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.cc
src/trace_processor/importers/proto/winscope/shell_transitions_tracker.h
src/trace_processor/importers/proto/winscope/winscope_context.h
src/trace_processor/importers/proto/winscope/winscope_geometry.cc
src/trace_processor/importers/proto/winscope/winscope_geometry.h
src/trace_processor/importers/proto/winscope/winscope_module.h
src/trace_processor/importers/proto/winscope/winscope_rect_tracker.cc
src/trace_processor/importers/proto/winscope/winscope_rect_tracker.h
src/trace_processor/importers/proto/winscope/winscope_transform_tracker.cc
src/trace_processor/importers/proto/winscope/winscope_transform_tracker.h

Winscope rect and transform trackers.
For parsing SF/VC/WM data into rect tables.
Bug: 411363817

Winscope rect and transform trackers

---

Android.bp
BUILD
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.cc
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.h

For processing layers in z order when computing rects and visibility.
Bug: 411363817

 SF layer extractor

---

src/base/watchdog_unittest.cc

Avoid volatile increment in test

---

Android.bp
gn/perfetto_android_sdk.gni
src/android_sdk/java/main/BUILD.gn
src/android_sdk/jni/BUILD.gn
tools/gen_android_bp
tools/gn_utils.py

We need this to generate almost identical build targets. E.g.: for 'libperfetto_jni' we want to generate the '3p' and 'framework' targets which differ only by the 'jarjar' config.
Tested in android tree:
`m perfetto_trace_lib`

Android.bp: support generation of 'defaults' for 'java_' and 'cc_' targets.

---

src/android_internal/cpu_time_in_state.cc
src/android_internal/cpu_time_in_state.h
src/traced/probes/android_cpu_per_uid/android_cpu_per_uid_data_source.cc

System server does this for us and doing so requires a bunch of permissions we don't have.
Bug: http://b/b422976190

Don't call startTrackingUidTimes().

---

src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.cc
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_extractor.h
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_utils.h

LayerDecoder provides greater clarity than ConstBytes. Also use optional Rect instead of pointer in GetCroppedScreenBounds.
Bug: 411363817

Update extractor to return LayerDecoder.

---

ui/src/assets/widgets/popup.scss
ui/src/base/semantic_icons.ts
ui/src/frontend/viewer_page/track_view.ts
ui/src/plugins/dev.perfetto.AndroidLog/index.ts
ui/src/plugins/dev.perfetto.Ftrace/index.ts
ui/src/plugins/dev.perfetto.Sched/index.ts
ui/src/public/track.ts
ui/src/widgets/popup.ts

If a `description` is provided when the track is registered, the help button appears in the track shell featuring a popup containing the provided description.
The description can be either a simple string or a function returning Mithril components in order to display rich text such as hyperlinks.
Fixes: https://buganizer.corp.google.com/issues/424382932
Example:

ui: Add track help button

---

docs/contributing/ui-plugins.md
ui/src/frontend/viewer_page/track_view.ts
ui/src/plugins/com.example.Tracks/index.ts
ui/src/public/track.ts

Also make `Track::getHeight()` optional to make it easier to define dummy renderers.

ui: Add docs for track help text / descriptions.

---

ui/src/assets/components/data_grid.scss
ui/src/components/widgets/data_grid/data_grid.ts

- The sort arrow is now a button, not just an icon. Clicking it inverts the sort direction on that column.
- When hovering over a column which we are not sorting by, a 'greyed out' sort arrow appears. Clicking it sorts the grid by that column.

ui: Improve column sorting UX

---

.github/actions/install-build-deps/action.yml

It's *not* fine to fallback on other cache results when
buildtools/BUILD.gn changes. Never allow the fallback.

github: separate BUILD.gn evaluation in hashing from install-build-deps

---

buildtools/BUILD.gn
gn/standalone/BUILD.gn
gn/standalone/BUILDCONFIG.gn

Generally, we build perfetto with -fno-rtti. However, this is incompatible with some UBSAN configurations, notably -fsanitize=vptr. Since we don't know if someone downstream will use -fsanitize=vptr, don't pass -fno-rtti when is_ubsan is true. This produces code which is compatible with clients using -fsanitize=vptr.
Bug: 422542836
Test: In ChromeOS chroot:
Test:     USE=ubsan emerge-$BOARD perfetto vulkan-shader-profiler
Change-Id: I1bf8950af457a708c93a30f6eefee1bff519cf4c

gn: Don't set -fno-rtti when is_ubsan is true

---

src/trace_processor/importers/common/process_tracker.cc

ProcessTracker has two GetThreadOrNull methods. One only takes a tid as an argument and the other takes a tid and an optional pid. Refactored the method so that it is clear that calling GetThreadOrNull(tid, std::nullopt) is the same as GetThreadOrNull(tid).
Bug: 425694654

Simplify GetThreadOrNull(tid) in process_tracker

---

src/trace_processor/importers/proto/packet_sequence_state_generation.h
src/trace_processor/importers/proto/track_event_module.cc
src/trace_processor/importers/proto/track_event_module.h
src/trace_processor/importers/proto/track_event_sequence_state.h
src/trace_processor/importers/proto/track_event_tokenizer.cc
src/trace_processor/importers/proto/track_event_tokenizer.h
src/trace_processor/importers/proto/track_event_tracker.cc
src/trace_processor/importers/proto/track_event_tracker.h
test/trace_processor/diff_tests/parser/track_event/incremental_counter_sequences.textproto
test/trace_processor/diff_tests/parser/track_event/tests.py

(cherry-picked from https://github.com/google/perfetto/pull/2002)
We were forcing incremental counter tracks to come from the same
sequence as incrementality does not make sense across sequences.
However, it's perfectly legit for two threads to have their own view of
the same counter: for example for thread timestamps.
This happens in practice when multiple libraries are independently using
the sdk and enabling chrome timestamps (e.g. webview + cronet).
Fix this by allowing for multiple sequences to contribute to the same
track with independent incremental values.

tp: don't require single sequence emission for incremental counter tracks (#2002)

---

Android.bp
BUILD
src/trace_processor/metrics/sql/android/wattson_app_startup_threads.sql
src/trace_processor/metrics/sql/android/wattson_atrace_apps_threads.sql
src/trace_processor/metrics/sql/android/wattson_markers_threads.sql
src/trace_processor/metrics/sql/android/wattson_trace_threads.sql
src/trace_processor/perfetto_sql/stdlib/wattson/BUILD.gn
src/trace_processor/perfetto_sql/stdlib/wattson/tasks/attribution.sql
src/trace_processor/perfetto_sql/stdlib/wattson/tasks/idle_transitions_attribution.sql
src/trace_processor/perfetto_sql/stdlib/wattson/tasks/task_slices.sql
src/trace_processor/perfetto_sql/stdlib/wattson/tasks/threads_w_processes.sql
test/trace_processor/diff_tests/stdlib/wattson/tests.py

In addition to threads/processes/packages, add IRQs as a potential task
for Wattson to attribute power for. This handles cases where tasks may
preempt another task, including for soft IRQs and hard IRQs.
Test: tools/diff_test_trace_processor.py out/linux/trace_processor_shell --name-filter '.*wattson.*'
Bug: 422478917
Signed-off-by: Samuel Wu <wusamuel@google.com>

stdlib: Add IRQ power attribution for Wattson

---

src/trace_processor/dataframe/dataframe_unittest.cc
src/trace_processor/dataframe/impl/bytecode_instructions.h
src/trace_processor/dataframe/impl/bytecode_interpreter_impl.h
src/trace_processor/dataframe/impl/bytecode_interpreter_unittest.cc
src/trace_processor/dataframe/impl/query_plan.cc

Just reverse the vector. Speeds up some queries where SQLite does not
correctly propogate LIMIT 1 to us.

tp: add optimization for descending sort on ordered column

---

src/trace_processor/util/proto_to_args_parser.cc
src/trace_processor/util/proto_to_args_parser.h
src/trace_processor/util/proto_to_args_parser_unittest.cc

For deeply nested messages, we are getting stack overflows for this. Fix by changing the implementation to be iterative instead.

tp: make ProtoToArgsParser iterative

---

Android.bp
BUILD
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_visibility_computation.cc
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_visibility_computation.h

Necessary to compute this for all traces until SF team provide visibility information directly on proto.
Bug: 411363817

SF layer visibility computation

---

src/trace_processor/containers/interval_intersector.h
src/trace_processor/containers/interval_intersector_unittest.cc
src/trace_processor/containers/interval_tree.h
src/trace_processor/containers/interval_tree_unittest.cc
src/trace_processor/perfetto_sql/intrinsics/functions/type_builders.cc
test/trace_processor/diff_tests/stdlib/intervals/intersect_tests.py

_interval_intersect macro will now return instants if there are instant results. Removed the dur > 0 check and added tests. If the interval (ts, dur) is (0, 10) it will return instant when it's inside it, (5, 0), but the ends are excluded, so there is no overlap with (10, 2).

tp: _interval_interesect supports instant events

---

test/trace_processor/diff_tests/parser/android/surfaceflinger_layers.textproto
test/trace_processor/diff_tests/parser/android/tests_surfaceflinger_layers.py
test/trace_processor/diff_tests/syntax/table_tests.py

Test rect computation at the table level, since it returns table ids and we want to check what data it actually added to the various Winscope tables.
Bug: 411363817

tp: table tests for SF parser changes

---

src/trace_processor/perfetto_sql/engine/dataframe_module.cc
src/trace_processor/perfetto_sql/engine/dataframe_module.h

Turns out this is causing a memory leak and it's very hard to fix this
in a way which does not do this. We really should fix this by uprevving
SQLite as much as possible.
This reverts commit e53f4da22a36c6c27ac7e3da1f505e9f84088f1e.

Revert "tp: add caching to deal with SQLite not reusing cursors (#1982)"

---

src/trace_processor/importers/json/json_trace_parser_impl.cc
src/trace_processor/importers/json/json_trace_tokenizer.cc
src/trace_processor/importers/json/json_trace_tokenizer.h
test/trace_processor/diff_tests/parser/json/tests.py

* fix parsing of string timestamps, we were causing an infinite recursion before
* fix parsing of global id2 values, we were comparing the wrong key before and also not correctly passing the id2 by ref
Add tests for all of this + some more things I spotted along the way.
Fixes: https://github.com/google/perfetto/issues/2067

tp: multiple small fixes for JSON trace tokenization (#2070)

---

src/trace_processor/importers/ftrace/ftrace_tokenizer.cc
src/trace_processor/importers/ftrace/ftrace_tokenizer.h

There are cases (e.g. ftrace_config.preserve_ftrace_buffer) when ftrace might
be timestamped using a non-boot clock, usually the default "local" clock.
Allow such traces in trace_processor, doing a best-effort clock sync to the
primary trace clock while treating the "local" clock as a sequence-scoped
clock. As a simplification, we don't track the clock separately per cpu as the
inter-cpu skew should be minimal for a cross-cpu trace to make sense in the
first place.
This is based on, and supersedes #1825.

tp: ftrace: allow for "local" ftrace clock (#1928)

---

src/trace_processor/perfetto_sql/stdlib/android/garbage_collection.sql

Bug: 429198070
android_garbage_collection_events labels 'Alloc young concurrent mark compact GC' GCs as 'young' GCs. These should be labeled as 'alloc' GCs instead, because the impacts on the app are much more like alloc GCs than young GCs.

Give 'Alloc young' gc_type alloc instead of young.

---

src/trace_processor/importers/json/BUILD.gn
src/trace_processor/importers/json/json_parser_unittest.cc
src/trace_processor/importers/json/json_trace_tokenizer.cc
src/trace_processor/importers/json/json_trace_tokenizer.h
test/trace_processor/diff_tests/parser/json/tests.py

We were missing this in the JSON parser rewrite.
Also add unittests for the parser and fix a small bug in timestamp
conversion for largish timestamps
Fixes: https://github.com/google/perfetto/issues/2092

tp: fix parsing of integer id2 values and large timestamps

---

ui/src/core/selection_manager.ts
ui/src/core/trace_impl.ts
ui/src/frontend/ui_main.ts

Add a new command to zoom in on selection. This is conceptually similar to focusing on events but also works on instant events.

ui: add command to zoom in on selection

---

ui/src/assets/widgets/popup.scss
ui/src/widgets/flamegraph.ts
ui/src/widgets/popup.ts

Added a `fitContent` attribute to the `Popup` widget which disables the max width.

ui: Fix flamegraph tooltip buttons overflowing off the tooltip

---

src/trace_processor/importers/proto/winscope/surfaceflinger_layers_parser.cc
src/trace_processor/tables/winscope_tables.py
test/trace_processor/diff_tests/parser/android/surfaceflinger_layers.textproto
test/trace_processor/diff_tests/parser/android/tests_surfaceflinger_layers.py

Bug: 427244076
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter="SurfaceFlingerLayer|PerfettoTable:winscope"

Parse SF corner radii separately.

---

ui/src/assets/components/data_grid.scss
ui/src/assets/widgets/stack.scss
ui/src/components/aggregation_panel.ts
ui/src/components/query_table/query_table.ts
ui/src/plugins/dev.perfetto.WidgetsPage/styles.scss
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/widgets/stack.ts

Fixed the datagrid's css so that the table scrolls, not the toolbar when space is limited, which means the toolbar / paging controls stay put and the table header stays pinned to the top when scrolling large pages.
Also fixed the widget layout to hide the overflow, limiting the size of widgets so that they get a chance to overflow and demonstrate scrolling.
Tested in the following places:
- Aggregation panels
- Query page
- Queries in the tab drawer
- Widgets page
- Explore page
Demo - notice the paging controls stay put while scrolling the table, and the table header sticks to the top when scrolling vertically, but says aligned with the columns when scrolling horizontally.
[e4c3f120-663d-4f3c-80f2-b79a45a1928f.webm](https://github.com/user-attachments/assets/30e445fe-4677-46a4-ab7e-c471d4 …

ui: Fix datagrid layout

---

ui/src/base/download_utils.ts
ui/src/frontend/post_message_handler.ts
ui/src/frontend/sidebar.ts

Also fix a bug in postmessage_handler, where we ignore 
localOnly: false, giving no option to the embedder to allow downloads.
Bug: b/430934358

UI: add file picker to the Download link in the sidebar

---

src/trace_processor/perfetto_sql/stdlib/android/memory/dmabuf.sql

This change adds an additional GLOB pattern to
match other variations of the process name.
Bug: b/430805731

Support more gralloc allocator process names

---

ui/src/plugins/dev.perfetto.Sched/thread_state_details_panel.ts

Uses standard padding and spacing container widgets to provide some padding around the button.

ui: Add standard padding around the 'Critical Path Lite' button

---

ui/src/plugins/dev.perfetto.AndroidDmabuf/index.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/index.ts
ui/src/plugins/org.kernel.SuspendResumeLatency/index.ts

It's the correct thing to group by instead of grouping by name.

ui: make use of newly added track_group_id column

---

ui/src/core/metatracing.ts
ui/src/frontend/sidebar.ts
ui/src/trace_processor/engine.ts

* fix enabling metatrace outside of always-on contexts
* stop logging on responses to enable metatrace request
* make detailed metatracing work if always-on or not
Fixes: https://github.com/google/perfetto/issues/2099

ui: several imporvements to UI metatracing

---

ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/fullTraceJankMetricHandler.ts
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinBlockingCall.ts
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinCujScoped.ts

- Previously, several pin commands would yield in seemingly randomly named tracks as such - "Debug Slice Track N"
- This is because slice's object passed to addDebugSliceTrack doesn't set trackName as "title"
Bug: 429513544
Test: Manual | Pin CUJ Scoped, FT or Blocking call metric (eg. perfetto_ft_systemui-missed_sf_frames) and check track name
Change-Id: I73ac01af9293fa14ae7d3bb8a2191048e057603a

PinAndroidPerfMetrics: Fix trackName on debug tracks

---

src/trace_processor/perfetto_sql/stdlib/android/critical_blocking_calls.sql
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/handlerRegistry.ts
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/metricUtils.ts
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinNotificationsBlockingCall.ts
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinNotificationsBlockingCall_unittest.ts

- Metrics prefixed `perfetto_android_notifications_blocking_call-blocking_calls-name-` are now handled by `dev.perfetto.PinAndroidPerfMetrics` plugin.
- This is already tracked and visualized by other tools. This CL allows perfetto to pin such metrics in the timeline.
- Other tools build the table in `android_sysui_notifications_blocking_calls_metric.sql` and use the value from the table 'android_sysui_notifications_blocking_calls'
- This CL however does not make use of it, to prevent use of `RUN_METRIC` in light of stdlib migration.
Bug: 352266918
Test: `./ui/run-unittests`
Test: Manual - load traces from b/379219510, pin metric "perfetto_android_notifications_blocking_call-blocking_calls-name-ExpNotRow#onNotifUpdated (leaf)-total_dur_ns-mean"
Change-Id: …

PinAndroidPerfMetrics: Add support to pin notifications_blocking metrics

---

ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinCujScoped.ts

- The regex allows for a metric with jankType as:
1. missed_frames
2. missed_sf_frames
3. missed_app_frames
- "missed_frames" is accepted but leaves the jankTypeFilter unassigned
- This makes the query append "undefined", which causes a UI Error
- Fix this by or-ing app_missed and sf_missed conditions for filter
Bug: 417567195
Test: Open any trace, pin any missed_frames metric, check for UI Error
Change-Id: Id8d88fb794df5de2f02df3cd4ce062a1fb3a24d1

PinAndroidPerfMetrics: Add default filter for "all" jankType

---

docs/getting-started/ftrace.md

Upstream renamed this API in commit 8fa7292fee5c ("treewide: Switch/rename to timer_delete[_sync]()").
Tested the updated example [only] on 6.16.0-rc5.

docs: adding ftrace tracepoints: fix example for linux v6.15+

---

src/trace_processor/metrics/sql/trace_metadata.sql

Emit 0 instead of null for sched duration
Handles a case where 24hrs traces in wear emits null sched duration as the sched table is empty

Emit 0 instead of null for sched duration

---

src/trace_processor/metrics/sql/android/jank/relevant_threads.sql

These tables are being used in telemtry scripts, and removing them causes breakages.

Re-add surfaceflinger tables related to jank metrics outside stdlib.

---

ui/build.js

Currently, only changes to styles.scss in plugins are automatically picked up by the build system and patched into the UI when running ui/run-dev-server. This is frustrating as it means plugin devs cannot split plugin styles into multiple files.
This change modifies the file watch regex to include all *.scss files in plugin dirs, and rebuilds and reloads the css when they change.

ui: Rebuild css when any *.scss files change inside plugins

---

ui/src/assets/components/data_grid.scss
ui/src/assets/widgets/box.scss
ui/src/assets/widgets/stack.scss
ui/src/base/semantic_icons.ts
ui/src/components/aggregation_panel.ts
ui/src/components/widgets/data_grid/data_grid.ts
ui/src/plugins/org.kernel.Wattson/aggregation_panel.ts
ui/src/widgets/box.ts
ui/src/widgets/common.ts
ui/src/widgets/stack.ts

- Reuse Stack and Box widgets instead of inventing our own.
- Add spacing attr to Box and Stack to adjust padding and gap size.
- Allow left and right toolbar items to be placed.
- Download icon on blob download button.

ui: Minor tweaks in DataGrid

---

Android.bp
protos/third_party/chromium/BUILD.gn

An upcoming Chrome patch will split chrome_track_event.proto into multiple files. This updates the build file so that patch won't fail when it's synced in:
Generate chrome_track_event.descriptor from a variable in sources.gni.
Add the current directory to import_dirs so that imports in the split files can be found.

Prepare to split chrome_track_event.proto into multiple files

---

ui/src/assets/widgets/icon.scss
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/widgets/icon.ts

This allows icons to be colored using the usual intent colors (primary, success, danger, warning).
Also make icons non-selectable, as folks usually don't want to select icons.

ui: Add intent coloring to Icon widgets

---

python/tools/check_ratchet.py
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/widgets/popper_utils.ts
ui/src/widgets/popup.ts
ui/src/widgets/tooltip.ts

The Tooltip widget provides a stripped down version of the Popup widget which only appears when the target is hovered. Useful as an alternative to the `title` attribute as it appears instantly and can contain any DOM elements.

ui: Add a Tooltip widget - a popup that appears only on hover

---

src/trace_processor/util/BUILD.gn

Regex unittests crash on Windows, this blocks Perfetto->Chromium autoroller (see http://crrev.com/c/6769677 for an example failure)

Don't run Regex unittests on Windows

---

src/tracing/track_event_category_registry.cc

Previous PR broke chrome autoroll
https://github.com/google/perfetto/pull/2159#pullrequestreview-3033403436
Because dynamic categories don't have a slow tag anymore. 
This PR fixes the tests by adding slow tag once again, only on dynamic categories with "disabled-by-default-"
prefix.
Bug: b/433191228

Fix adding slow tag to dynamic categories

---

protos/third_party/chromium/chrome_track_event_import_wrapper.proto
protos/third_party/chromium/optimization_guide/.clang-format-ignore

Copybara import from Chromium: proto and stdlib changes
COPYBARA_IMPORT=Project import generated by Copybara.
GitOrigin-RevId: be68446e180370c868646c13119523a3d9741a44

Copybara import from Chromium: proto and stdlib changes

---

protos/third_party/chromium/.clang-format-ignore

copybara was deleting the clang-format-ignore file so move it to the parent to ensure it remains.

Move .clang-format.ignore into parent directory

---

src/trace_processor/util/BUILD.gn
src/trace_processor/util/murmur_hash.h

FNV1A is not cutting it:
* we're spending a lot of time in HashString when parsing traces
* our hashmaps are doing poorly because of collisisons because it's not
high quality enough
* HLL was failing tests likely because of hash function diffusion not
being strong enough.
This hash function is murmurhash inspired (it's most heavily based on
implementation in duckdb) and should be a lot better interms of both
performance (as it operates 8 bytes at a time) and quality (as
murmurhash is a much better hash function in quality)

tp: add new murmurhash implementation

---

python/generators/diff_tests/runner.py
tools/serialize_test_trace.py

When a test fails, the framework tells you how to serialize the trace. The command given by the framework is broken if the trace uses extensions. For example, when the diff_test
`WindowManager:has_expected_rows` fails, the suggested command fails to generate the trace.
This commit fixes the problem.

diff_tests: Include extra descriptors in serialize_test_trace command

---

.github/actions/install-build-deps/action.yml
src/base/scoped_sched_boost_unittest.cc

Otherwise the cache is never restored when running the `actions/cache/restore@v4`
inside the `./.github/actions/install-build-deps` action.

github: fix a typo in the 'Save build-deps' action key.

---

ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_data_viewer.ts

QueryTable was a wrapper around DataGrid, there was no need to use it. This is the first step of the refactor of node_data_explorer, that didn't require changing DataGrid

exp: Use DataGrid directly in NodeDataExplorer

---

ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_data_viewer.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/operations/filter.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/query_node_explorer.ts

Filtering node can be applied both from table and from QueryNodeExplorer

exp: Propagate table filters to NodeExplorer filters

---

include/perfetto/ext/base/murmur_hash.h
src/base/murmur_hash_unittest.cc

This CL does three things:
1) **Switch murmur implementation to faithful mmh64**
The custom implementation from DuckDB sadly was causing trivial collisions in some real world traces. Use the actual implementation of MMH64 which at least means we are depending on something reliable.
2) **Add MurmurHashCombiner to combine multiple values**
The combine function is taken from boost::hash_combine and we use it to combine multiple mm64 hashes.
3) **Add MurmurHash to act as a drop in implementation to std::hash**
The class we're going to use in base::FlatHashMap to act as a hash. Uses the mixing function for integers, mm64 for strings and std::hash for everything else (though we should really add a absl like implementation to allow arbitrary types to be hashed).

base: prepare murmurhash to actually be ready to use

---

include/perfetto/ext/base/flags.h
include/perfetto/ext/base/flat_hash_map.h
include/perfetto/ext/base/murmur_hash.h
src/base/murmur_hash_unittest.cc

This CL makes the necessary change to start using MurmurHash for base::FlatHashMap behind an Android platform flag. On non-Android platforms, we enable it by default.

tp: use MurmurHash for base::FlatHashMap behind a flag

---

include/perfetto/ext/base/flags.h
include/perfetto/ext/base/flat_hash_map.h
include/perfetto/ext/base/murmur_hash.h
src/base/murmur_hash_unittest.cc
src/trace_processor/containers/string_pool.h
src/trace_processor/importers/common/global_args_tracker.h

These are some of the most CPU hot places in trace processor, switching to MurmurHash improves load performance on a large CPU/arg heavy trace by ~7% (47s -> 44s).

tp: switch args hashing and string pool hashing to MurmurHash

---

Android.bp
Android.bp.extras

The dependent targets have this so make it so here as well.

perfetto: fix flags target to be vendor and product avaialble

---

include/perfetto/ext/base/murmur_hash.h

THe memcpy should be optimized away by the compiler but should stop
ubsan from crashing

base: fix ubsan complaints in murmurhash

---

ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_box.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_graph.ts

We stopped visalising node correctly some time ago, so remove it until we implement it for the new version of Explore Page

exp: Remove the option to visualize node

---

ui/src/core/trace_impl.ts
ui/src/frontend/post_message_handler.ts
ui/src/plugins/org.chromium.ChromeScrollJank/scroll_jank_cause_link_utils.ts
ui/src/public/scroll_helper.ts

All usages have been replaced with trace.scrollTo()

ui: Remove global scrollTo() function

---

src/trace_processor/importers/common/clock_tracker.cc

Instead of adding a ton of clocks only to immediately return the first, just directly return the first clock if it matches the target
Fixes perf on large chrome traces which have a ton of snapshots. Takes load time on trace from b/433757600 from 27s -> 16s.
Fixes: 433757600

tp: significantly improve load perf of traces with lots of snapshots

---

src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql
test/trace_processor/diff_tests/parser/power/tests_power_rails.py

The current table contains one row per sample making it non-ideal for looking information about power rail tracks. In addition it does not have any info about the rail subsystem or other metadata.
Add a new table to make it easy to query this info.

stdlib: Add table for power rail metadata

---

docs/contributing/developer-tools.md

this should be "git update-stack" not "git-update-stack" assuming
this is supposed to depend on the aliases set earlier in the doc.

docs: fix git update-stack command in developer tool docs

---

src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql

Because we want to use the stdlib in the PowerRails UI plugin, and
we want to ensure this plugin is machine id aware, add the machine
id to the power rail metadata.
Bug: #2249

stdlib: add machine_id to android_power_rails_metadata

---

protos/third_party/.clang-format-ignore

This change moves .clang-format-ignore from chromium into the parent directory to prevent it from being overwritten by rolls from chromium. Also updates the path to point inside chromium.

Move .clang-format-ignore from chromium into third_party

---

src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql
test/trace_processor/diff_tests/parser/power/tests_power_rails.py

There exists a map of raw to userfriendly name in
https://github.com/google/perfetto/blob/0c893ed6bf6b42e3fee58daf3380d301c72550ed/src/trace_processor/importers/proto/android_probes_module.cc#L59-L120
We would like to expose these names to users of the stdlib without the
"power.rails." prefix which is part of the track name itself.
It is possible these user friendly name mappings should be moved into
the stdlib instead of mapping in trace processor, but it is possible
consumers of the power rails are referencing the track names in SQL
already so that will be left to a future change.
This PR mainly aims to create an API to get the userfrienly name that
can be depended upon by the ui regardless of if this mapping logic is
in trace processor or in the stdlib.
#Bug: 2249

stdlib: expose userfriendly power rail names.

---

include/perfetto/base/platform_handle.h
include/perfetto/ext/base/file_utils.h
src/base/ctrl_c_handler.cc
src/base/event_fd.cc
src/base/file_utils.cc
src/base/paged_memory.cc
src/base/pipe.cc
src/base/scoped_mmap.cc
src/base/string_utils.cc
src/base/subprocess_unittest.cc
src/base/subprocess_windows.cc
src/base/temp_file.cc
src/base/test/vm_test_utils.cc
src/base/thread_checker.cc
src/base/thread_utils.cc
src/base/threading/channel_unittest.cc
src/base/time.cc
src/base/unix_socket.cc
src/base/unix_task_runner.cc
src/base/utils.cc
src/base/utils_unittest.cc
src/profiling/symbolizer/filesystem_windows.cc
src/profiling/symbolizer/subprocess_windows.cc
src/tracing/ipc/shared_memory_windows.cc
src/tracing/platform_windows.cc
src/tracing/test/api_integrationtest.cc
src/tracing/test/api_test_support.cc
test/stress_test/stress_test.cc

Upstreaming patches from JuliaPackaging/Yggdrasil#11770. One remaining
issue is that `NetworkPacketEvent_Decoder` in the sdk header defines a
member function with the name `interface`, which conflicts with a mingw
macro, but I wasn't able to figure out from where that definition was
generated

fix mingw builds

---

src/trace_processor/perfetto_sql/stdlib/android/power_rails.sql
test/trace_processor/diff_tests/parser/power/tests_power_rails.py
ui/src/plugins/dev.perfetto.PowerRails/index.ts
ui/src/plugins/dev.perfetto.PowerRails/power_counter_selection_aggregator.ts

Pixels have several of their rails mapped to user frienly names in
trace processor which show up in the default track names. when we
moved to a dedicated PowerRails plugin these names disappeared in
favor of the raw name.
Since the goal of this plugin was user friendliness, bring back the
user friendly rail names, however without the "power.rails." prefix this
time, both because it is redundant and because some of the track
names would not fit in the allocated space in the UI and would need
to be partially truncated.

ui: Display user friendly power rail names.

---

ui/src/assets/widgets/grid_layout.scss

When rendering the args tree with renderArguments, long value texts overflow outside the GridLayoutColumn component. This update adds CSS styling to enable automatic word-level wrapping, ensuring the content stays within the column boundaries.
Before: 
After:

ui: Fix content overflow in current selection panel's GridLayoutColumn

---

gn/perfetto.gni

Adds mutual exclusion between the flags enable_perfetto_llvm_symbolizer and use_custom_libcxx.
enable_perfetto_llvm_symbolizer is not compatible with use_custom_libcxx because the former dynamically links to system llvm which is compiled using libstdc++ which makes it incompatible with building using libcxx.

tp: build: mutual exclusion of llvm_symbolizer and libcxx flags

---

CHANGELOG

Before: all ftrace data (inline sched waking, inline sched switch, ftrace events) was placed onto a shared set of per-cpu queues in the sorter. Also track event and track packet shared a sorter queue.
After: each type of data is is given its own queue: in the case of ftrace, it's given independent per-cpu queues (i.e. waking, switch and normal ftrace events each get their own set of per-CPU queues).

changelog: tp: highlight identical ts sorting edge case from ffb178a1a3

---

src/trace_processor/perfetto_sql/stdlib/wattson/cpu/estimates.sql
src/trace_processor/perfetto_sql/stdlib/wattson/cpu/pivot.sql
src/trace_processor/perfetto_sql/stdlib/wattson/cpu/w_cpu_dependence.sql
src/trace_processor/perfetto_sql/stdlib/wattson/cpu/w_dsu_dependence.sql
src/trace_processor/perfetto_sql/stdlib/wattson/curves/utils.sql
src/trace_processor/perfetto_sql/stdlib/wattson/device_infos.sql

Get the frequency that corresponds to the static vote (for both 1D and
2D dependent policies) generically instead of assuming it will be on
CPU0.
Additionally, handle the cases where there are multiple static values
coming from both the 1D and 2D policies.
Bug: 434979529
Signed-off-by: Samuel Wu <wusamuel@google.com>

stdlib: Make static_freq generic across CPUs

---

include/perfetto/ext/base/status_macros.h

We can use the macros from other namespaces (i.e. `protozero`).

base: Fix status_macros for non-perfetto namespace

---

include/perfetto/base/time.h

The check uses `__MAC_OS_X_VERSION_MIN_REQUIRED` without checking if its defined. In an iOS build, the macro won't be defined so it'll evaluate to 0, and so the check will always evaluate to true. That version of GetThreadCPUTimeNs will trip up the sandbox for Chromium iOS blink.

Fix macro condition for pre-macOS-10.12 GetThreadCPUTimeNs

---

src/android_stats/perfetto_atoms.h
src/tracing/service/tracing_service_impl.cc

Add atoms:
- kTracedEnableTracingExclusiveSessionRejected
- kTracedEnableTracingExclusiveSessionNotAllowed

tracing: Log exclusive session rejection.

---

ui/src/assets/perfetto.scss
ui/src/assets/widgets/code_snippet.scss
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/widgets/code_snippet.ts

Adds a code snippet widget with builtin scrolling and a copy button.

ui: Add code snippet widget

---

include/perfetto/ext/base/status_macros.h
src/trace_processor/importers/proto/gpu_event_parser.cc
src/trace_processor/importers/proto/gpu_event_parser.h
test/trace_processor/diff_tests/parser/graphics/gpu_render_stages_overlapping.py
test/trace_processor/diff_tests/parser/graphics/tests_gpu_trace.py

The SliceTracker was silently dropping overlapping gpu_render_stage_event
slices that occurred on the same hardware queue.
This change moves the gpu_render_stage event parsing to use the
TrackCompressor API. To prevent overlaps, TrackCompressor creates the
minimal number of tracks necessary for a given hardware queue, placing
conflicting slices on different tracks. These tracks are associated with
the same hw_queue_id, allowing the UI to compress them into a single
visual track with stacked events. This ensures no slice data is lost.
A new diff test is added to verify that two overlapping events on the
same hw_queue_id are both processed and appear correctly in the
gpu_slice table.
Fixes: https://github.com/google/perfetto/issues/2473

tp: Fix overlapping gpu_render_stage slices being dropped

---

python/generators/diff_tests/runner.py
python/generators/diff_tests/test_loader.py
python/generators/diff_tests/utils.py
tools/diff_test_trace_processor.py

Chrome's run_perfetto_diff_tests script passes --test-dir to use a custom set of tests in an include_index.py file from the chromium repo. However after the refactor in commit
c73249ac86b183522a7aed9fbde127d8e3f65848, --test-dir is ignored and the script runs the complete set of diff tests from
test/trace_processor/diff_tests/include_index.py, most of which aren't supported from Chrome.
This fixes the problem by making sure --test-dir is passed through to TestLoader:
* TestLoader's test_data_dir param is never used (all its methods actually use blueprint.test_data_dir). Remove it.
* discover_and_load_tests from the same TestLoader should always look in the same dir, so move its root_dir param to the constructor, replacing test_data_dir.
* Fix DiffTestsRunner to pass config.test_dir, which …

Fix path handling in discover_and_load_tests.

---

python/generators/diff_tests/runner.py

Fixes an exception thrown from write_cmdlines if a difftest fails:
```
NameError: name 'config' is not defined. Did you mean: 'Config'?
```
The regression was introduced in commit 3e17997fd8523ee042707dd1a53172bd560b1951

Fix exception in write_cmdlines

---

python/generators/diff_tests/testing.py

Fix the last issue with python code copyright headers, which in this
case is a duplicated line.
The aim here is to get the header for testing.py to match the other
python files.

fix remaining copyright header issue in python code.

---

ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/pinBlockingCall.ts

The metric raises alerts on the mean value of the metric. Fixed the constant string with the '-mean' suffix.
Bug: 394866952
Test: manual plugin test for a sample trace

Fix max_duration_per_frame 'aggregation' constant.

---

ui/build.js

- Fix bug where durations would wrap after 60sec.
- Switch to the monotonic performance.now() rather than Date.now().
This allows us to accurately measure how long things take on the CI.

ui: Fix millisecond timestamp printing in build.js

---

src/trace_processor/perfetto_sql/stdlib/android/frames/jank_type.sql
ui/src/plugins/dev.perfetto.PinAndroidPerfMetrics/handlers/fullTraceJankMetricHandler.ts

- This commit fixes a discrepancy where the "all missed frames" track in the UI plugin showed more frames than the official `missed_frames` metric, causing confusion during analysis.
- The track previously used a broad `display_value != 'None'` filter, which included non-severe jank types (e.g., Delayed Frames) that the metric intentionally excludes.
- A new standard SQL function, `android_is_missed_frame_type`, is introduced to encapsulate the metric's precise definition of a missed frame.
- The UI plugin is updated to use this new function, ensuring the visual track and the metric count are now consistent.
Bug: 435429713
Test: Manual - Rebuild Perfetto and open a trace with jank and pin perfetto_ft_systemui-missed_frames. Verify the number of distinct slices on the track now matches the …

TraceProcessor: Fix "all missed frames" track count to match metric

---

ui/src/components/tracks/base_counter_track.ts
ui/src/plugins/dev.perfetto.CpuFreq/cpu_freq_track.ts

Fixes a mistake in #2541 where the counter track labels were being drawn in with no alpha, whereas before they had an alpha value of 0.6. The PR sets the alpha values for both counter tracks to 0.6.

ui: Fix alpha levels on counter track labels

---

tools/git_set_parent.py

Setting the parent to a branch that does not exist can cause all
of the stack related tools to fail when updating or syncing if one
of the parents don't exist.
To help mitigate the impact of user errors, prevent the user from
setting an invalid branch vs erroring later.

tools: make git_set_parent error on invalid input branch

---

ui/src/plugins/com.google.PixelMemory/index.ts

- Adds support for analyzing multiple PIDs simultaneously.
- When multiple PIDs are provided, creates an aggregated "Total" track showing their combined memory usage.
- Automatically adds a visual annotation to the timeline to mark the point of maximum memory.
Bug: 437214050
Test: run plugin and verify the result with single/multiple pids

ui: plugin: Enhance PixelMemory to support multiple PID inputs

---

ui/src/base/time.ts
ui/src/base/time_unittest.ts

To better support longer durations, add support for printing years
and days if the selected time period is large enough.

ui: support larger time units in selection duration.

---

src/trace_processor/importers/art_method/art_method_parser.cc
src/trace_processor/importers/common/process_tracker.cc
src/trace_processor/importers/common/process_tracker.h
src/trace_processor/importers/ftrace/ftrace_parser.cc
src/trace_processor/importers/generic_kernel/generic_kernel_parser.cc
src/trace_processor/importers/perf_text/perf_text_trace_parser.cc

ProcessTracker should rely more on UniqueTids given they disambiguate the thread in question since Perfetto allows concurrent tids.
Bug: 425694654

Refactor UpdateThreadNameAndMaybeProcessName to use UniqueTid

---

python/generators/diff_tests/models.py
python/generators/diff_tests/runner.py
python/generators/diff_tests/test_loader.py
python/generators/diff_tests/testing.py
test/trace_processor/diff_tests/include_index.py
test/trace_processor/diff_tests/parser/etm/tests.py
test/trace_processor/diff_tests/stdlib/symbolize/tests.py
tools/diff_test_trace_processor.py

Adds conditional diff tests based on the modules in the current build.
DiffTestBlueprint now has a new field named modules where a list of module names can be provided for each diff test.
This PR is designed to resolve #2381 and should allow for #2382 while preventing situations like #2478.

tp: diff_tests: adds optional diff tests based on config

---

src/trace_processor/export_json_unittest.cc
src/trace_processor/importers/common/track_compressor.cc
src/trace_processor/importers/common/track_compressor.h
src/trace_processor/importers/common/track_compressor_unittest.cc
src/trace_processor/importers/proto/network_trace_module_unittest.cc
src/trace_processor/importers/proto/proto_trace_parser_impl_unittest.cc
src/trace_processor/trace_processor_context.cc
src/trace_processor/types/trace_processor_context.h

We should ensure they are put in differnt sets to ensure we don't end up
with multiple traes both assigning group 0

tp: fix clashing of track group ids across traces

---

tools/run_presubmit

When running presubmit checks, we currently check changed files between HEAD and (by default) origin/main. However, if you're working on an older branch and origin/main has moved on, this diff can include changes that are not part of your branch.
This patch changes the presubmit checks to diff against the merge-base (i.e. the closest common ancestor between origin/main and HEAD, so that it includes only the files you've changed in your branch.

infra: Run presubmit diff against the merge-base of HEAD and origin/main

---

python/tools/record_android_trace.py
tools/record_android_trace

when we use the tools/record_android_trace, it will be good we can pass the url params when open the trace in the browser. This is part of change for this feature rquest ([2400](https://github.com/google/perfetto/issues/2400)) . 
The default value are the same as before, so there is no logic changes.
**Test:**
run the script: ./gen_amalgamated_python_tools to generate the record_android_trace and tested with an Android device trace, all works as expected.
When pass the url-params with cmd: `tools/record_android_trace -c perfetto.config --url-params test1 test2 test3`, the url-params is append to the url correctly in the browser.

Add url params option for the record android trace script

---

ui/src/components/aggregation_adapter.ts

Fixes a race in the aggregator when prepareData() calls us more than one query to tear down and bring up the table.

ui: Fix race in aggregator

---

src/trace_processor/importers/proto/chrome_string_lookup.h

The ProcessType and ThreadType enums have been moved to chrome_enums.proto. Cleans up some comments using the old names.

Remove missed ChromeProcessDescriptor::ProcessType reference

---

ui/src/assets/components/json_settings_editor.scss
ui/src/assets/perfetto.scss
ui/src/components/json_settings_editor.ts
ui/src/core/app_impl.ts
ui/src/core/command_manager.ts
ui/src/core/fake_trace_impl.ts
ui/src/core/load_trace.ts
ui/src/core/omnibox_manager.ts
ui/src/core/trace_impl.ts
ui/src/core_plugins/commands/index.ts
ui/src/frontend/index.ts

- Add startup commands feature that executes commands after trace load
- Create reusable JsonSettingsEditor widget for JSON-based settings
- Refactor macro settings to use the new widget and shared schemas
- Add command validation with improved error reporting grouped by macro
- Use z.infer to keep TypeScript types in sync with Zod schemas
- Consolidate command invocation schemas in command_manager.ts
- Add proper JSDoc documentation for all new interfaces and functions
- Update macro execution to use command IDs instead of names for consistency
Bug: https://github.com/google/perfetto/issues/1342
Bug: https://github.com/google/perfetto/issues/2551

ui: implement startup commands feature

---

src/trace_processor/perfetto_sql/stdlib/export/to_svg.sql

For some reason, the macros are unhappy with cast( AS STRING).
Switching to cast_string!() fixes
Test: tools/diff_test_trace_processor.py out/android/trace_processor_shell --name-filter '.*svg.*'
Change-Id: I9c08123dbbb7d5ce19940375e2bb62989e4922db

stdlib: Fix to_svg sql

---

src/trace_processor/importers/proto/track_event_tracker.cc

This PR fixes Unreachable error by adding a missing early return when trakc merging is disabled.
https://buganizer.corp.google.com/issues/440315270

[track] Fix Unreachable error in MergedKey

---

src/trace_processor/importers/proto/track_event_tracker.cc

This PR fixes Unreachable error by adding a missing early return when
trakc merging is disabled.
https://buganizer.corp.google.com/issues/440315270
Cherry-pick of https://github.com/google/perfetto/pull/2687

[track] Fix Unreachable error in MergedKey (#2687)

---

python/tools/record_android_trace.py
tools/record_android_trace

- Add --ui-startup-commands argument to execute commands on UI startup
- Rename --url-params to --ui-url-params and mark as advanced
- Add JSON validation and URL encoding for startup commands
- Support startupCommands URL parameter for browser-based trace automation
- Import json and urllib.parse modules for new functionality
This enables automated UI actions when traces are opened in the browser,
such as pinning tracks by regex patterns or other UI scripting operations.

python: Add UI startup commands support to record_android_trace.py

---

src/base/task_runner_unittest.cc

- Turn the test into a typed test. In the next CLs
this will test two implementations, the existing and
the new LockFreeTaskRunner.
- Add some more tests about some edge cases I worked out
while developing LockFreeTaskRunner.
Bug: b/394504259

base: Improve TaskRunner tests

---

src/trace_processor/perfetto_sql/intrinsics/operators/etm_decode_trace_vtable.cc

This PR fixes an issue with how cumulative cycle counts was calculated in EtmDecodeChunkVtable.
The issue was that during a JOIN with other tables the cumulative cycle count column would always be null.

tp: etm: fix cycle count for joins

---

include/perfetto/trace_processor/trace_blob_view.h
include/perfetto/trace_processor/trace_processor.h
src/trace_processor/importers/common/registered_file_tracker.cc
src/trace_processor/importers/common/registered_file_tracker.h
src/trace_processor/importers/etm/mapping_version.cc
src/trace_processor/importers/etm/mapping_version.h
src/trace_processor/importers/etm/virtual_address_space.cc
src/trace_processor/trace_processor_impl.cc
src/trace_processor/trace_processor_impl.h
src/trace_processor/trace_processor_shell.cc
src/trace_processor/util/elf/binary_info.cc

As a temporary fix for b/438916722.
ETM registers files with large sizes causing TraceBlobView size to become truncated. This means we can not trust any of the below checks for large files. So a solution is needed that is not too expensive memory wise.
This PR converts these from errors to warnings and adds a TODO to find a memory efficient fix later.

tp: etm: binary info error fix

---

tools/run_presubmit

In https://github.com/google/perfetto/pull/2623, we added logic to prevent picking up unnecessary changes locally when origin/main had diverged but the local branch had not merged back. Unfortunately this logic does not work on the CI which does a shallow clone.
If getting the merge base commit fails, just use the merge_base passed in directly.

tools: fix presubmit script on contributions from external folk

---

src/trace_processor/importers/common/tracks_common.h
src/trace_processor/importers/ftrace/ftrace_parser.cc
src/trace_processor/importers/systrace/systrace_line_parser.cc
test/trace_processor/diff_tests/parser/sched/cpu_frequency_limits.systrace
test/trace_processor/diff_tests/parser/sched/cpu_frequency_limits_test.sql
test/trace_processor/diff_tests/parser/sched/tests.py

Parse the cpu_frequency_limits ftrace event from systrace, and show it on the Perfetto UI in the same way as from proto.
Test: tools/diff_test_trace_processor.py <trace_processor_shell> --name-filter='SchedParser:cpu_frequency_limits_from_systrace'
Background: When loading Android Systrace using PerfettoUI, the cpu_frequency_limits event is not parsed and displayed in PerfettoUI, whereas it is parsed when loading Perfetto. This commit adds parsing for the cpu_frequency_limits event in Android Systrace. The effect after the commit is shown below:

Parse the cpu_frequency_limits ftrace event from systrace

---

docs/toc.md
docs/visualization/commands-automation-reference.md
docs/visualization/deep-linking-to-perfetto-ui.md
docs/visualization/perfetto-ui.md
docs/visualization/ui-automation-cookbook.md

This page adds a doc for the set of commands we want to maintain stable
back-compat guarantees for into the future. Any command in this docs
should also have a startup commands test in the UI codebase.

ui: add reference for stable set of commands for automation purposes

---

BUILD.gn

Running `tools/gen_all` when doing a cross compilation (for example, for android) fails, because protozero_c_plugin is missing.
This commit fixes the problem.
Suggested-by: cairno@google.com

BUILD.gn: Fix `tools/gen_all` with cross compilation

---

include/perfetto/tracing/track_event_legacy.h

Profiling of Chrome shows that about 5% of the cycles used by Perfetto tracing is in the TrackEventCategoryRegistry::StringEq method, which is constexpr and documented to be intended for compile-time category lookups. Since it's showing up in runtime traces, it's not always being executed at compile time.
The root cause is that there are two global TrackEventCategoryRegistry objects, `kConstExprCategoryRegistry` for compile-time lookups and `kCategoryRegistry` for runtime lookups. In theory a single constexpr object could be used for both purposes but due to https://bugs.llvm.org/show_bug.cgi?id=51558 the object that includes a pointer to runtime state data can't be constexpr. (See comments in track_event_macros.h.)
StringEq() is only called from the Find() method, which is only called in …

Always use constexpr category registry with Find

---

include/perfetto/tracing/track_event_legacy.h

This reverts commit d23c5621543830bd4c83bbf358150b7cc713f09a.
It's breaking the perfetto -> chrome autoroller because it adds 300k of binary size on 32-bit Android builds, which is blocked by policy.
Will need to either make the fix conditional or sort out a policy change before relanding it.

Revert "Always use constexpr category registry with Find (#2735)"

---

src/trace_processor/importers/perf_text/BUILD.gn
src/trace_processor/importers/perf_text/perf_text_trace_tokenizer.cc

Required when merging multiple traces together.

tp: perform trace time conversion, assuming MONOTONIC for perf text

---

ui/src/core/app_impl.ts
ui/src/plugins/dev.perfetto.AutoPinAndExpandTracks/index.ts
ui/src/public/app.ts
ui/src/public/route_schema.ts

- Omit the number type from initialPluginRouterArgs value type, as our
URL parser can never generate numbers (only strings and booleans).
- Export RouterArg type for convenience.
- Tidy up usage of these args in dev.perfetto.AutoPinAndExpandTracks.

ui: Tidy up initialPluginRouteArgs

---

src/trace_processor/importers/perf_text/perf_text_trace_tokenizer.cc

I'd like us to be pedantic when guessing/assuming clocks going forward.
Here's my interpretation for "3abf62f957 tp: perform trace time
conversion, assuming MONOTONIC for perf text (#2759)"

tp: perf_text: document clock assumptions

---

src/trace_processor/importers/perf_text/perf_text_trace_tokenizer.cc

We were not correctly popping the read data on failure meaning it was
possible to get stuck in an infinite loop in the tokenizer.

tp: fix subtle bug with perf text format

---

src/tracebox/tracebox.cc

Unfortunately, does not wok as-is because tracebox does not cleanup
sockets after stopping.
This reverts commit a7a47e439169764233dda9681ef0df1cf5187aef.

Revert "tracebox: improve default behaviour of tracebox on non-Android (#2747)"

---

src/trace_processor/perfetto_sql/stdlib/linux/perf/samples.sql

Required as just below we join on parent_id. If the join happens the
wrong way around, we need this to be fast.

tp: add missing index on parent id for perf samples

---

src/trace_processor/importers/common/flow_tracker.cc
src/trace_processor/importers/common/flow_tracker_unittest.cc
test/trace_processor/diff_tests/tables/tests.py

Flows should always go from earlier to later timestamps. Previously,
flows could go backwards in time when Step() or End() was called with
a slice that had an earlier timestamp than the existing flow slice.
This fix compares slice timestamps in both Step() and End() methods
and ensures the flow direction is always chronologically correct by
setting the earlier timestamp slice as outgoing and the later one as
incoming.
Added comprehensive unit and diff tests that verify:
- Flows are correctly ordered by timestamp
- Tests fail without the fix (backwards flows)
- Tests pass with the fix (correct chronological direction)
- No regressions in existing flow functionality

tp: fix flow tracker direction by comparing timestamps

---

src/trace_processor/perfetto_sql/stdlib/linux/perf/samples.sql
ui/src/components/query_flamegraph.ts
ui/src/plugins/dev.perfetto.CpuProfile/cpu_profile_details_panel.ts
ui/src/plugins/dev.perfetto.CpuProfile/index.ts
ui/src/plugins/dev.perfetto.HeapProfile/heap_profile_details_panel.ts
ui/src/plugins/dev.perfetto.InstrumentsSamplesProfile/instruments_samples_profile_track.ts
ui/src/plugins/dev.perfetto.LinuxPerf/index.ts
ui/src/plugins/dev.perfetto.LinuxPerf/perf_samples_profile_track.ts

* instead of returning null for when there are multiple source files,
return a summary at least indicating the first line
* use distinct to detect if the same file is repeated many times instead
of relying on a simple count
* switch line number to use concat_with_comma: line numbers are small
enough and infrequent enough to just list all of them.

ui: improve how source/line number aggregation works

---

ui/src/plugins/dev.perfetto.CriticalPath/index.ts

LEFT JOIN to allow correct behaviour even when process names are not
collected (e.g. in other trace types)

ui: don't require process name for critical path

---

ui/src/core/trace_impl.ts
ui/src/public/app.ts

This allows normal plugins (not core plugins) to be able to access the isInternalUser flag on the App and Trace objects.

ui: Make the isInternalUser flag available to regular plugins

---

ui/src/plugins/com.android.AndroidStartup/index.ts

Otherwise we're slowing down other trace types for no reason.

ui: only run breakdown if there is a startup in trace

---

ui/src/plugins/dev.perfetto.QueryPage/query_page.ts
ui/src/plugins/dev.perfetto.WidgetsPage/widgets_page.ts
ui/src/widgets/copy_to_clipboard_button.ts

A button that copies text to the clipboard when clicked and also provides some visual feedback.

ui: Add CopyToClipboardButton widget

---

ui/src/base/bezier_arrow.ts
ui/src/frontend/viewer_page/flow_events_renderer.ts

Currently, flow arrowheads are omitted when the start and end points are close together, but the proximity check only considers the x-axis distance. This causes arrowheads to be hidden even when flows span different tracks with adequate vertical separation, making it difficult to discern arrow direction.
This patch calculates wether the start and end points are far enough away in _either_ axis, instead of using only the x-axis distance to determine whether to render the arrowhead.
Also fixed a bug in the arrowhead rendering logic where the arrow body emerges from the arrowhead tip instead of the back of the arrowhead.
Before:
Arrowhead presence logic fised (but with arrowhead rendering bug):
Final:

ui: Fix flow arrowhead rendering for vertical arrow separation

---

ui/src/plugins/dev.perfetto.Sched/cpu_slice_selection_aggregator.ts

On a systrace/raw ftrace, there's no process info but this view should
still work.

ui: fix cpu slice aggregation with no processes

---

ui/src/frontend/viewer_page/track_tree_view.ts

ui: Fix bug where child track titles stick to the wrong place inside non-summary track groups

---

src/trace_processor/perfetto_sql/intrinsics/functions/structural_tree_partition.cc

During the Step phase, the code builds a child_count_by_id vector to store the number of children for each node. It correctly resized this vector whenever it saw a non-root node with an ID larger than the vector's current size. However, it missed doing this check for the root node (the one with a NULL parent).
If the root node happened to have the largest ID in the entire tree, the child_count_by_id vector was never made large enough to include its ID. This led to a crash in the Final phase, which would try to read from an out-of-bounds index in that vector when processing the root node's children, causing the segmentation fault.
The fix was to add the missing size check for the root node in the Step function so that when the root node is found, the child_count_by_id vector is resized to …

tp: Fix segfault in tree partition

---

ui/src/core_plugins/dev.perfetto.CoreCommands/index.ts

- Remove plugin.name prefix for a command
- Use trace instead of app in various commands

ui: Small tidy up in coreCommands

---

Android.bp
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_test_utils.h
src/trace_processor/importers/proto/winscope/winscope_geometry.cc
src/trace_processor/importers/proto/winscope/winscope_geometry_test_utils.h
src/trace_processor/importers/proto/winscope/winscope_geometry_unittest.cc

Surfaced during Flicker test cleanup.
Bug: 312910010
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter="SurfaceFlingerLayer|PerfettoTable:winscope"
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=WinscopeGeometry*

Winscope geometry fixes.

---

src/trace_processor/perfetto_sql/stdlib/linux/cpu/utilization/process.sql
src/trace_processor/perfetto_sql/stdlib/linux/cpu/utilization/slice.sql
src/trace_processor/perfetto_sql/stdlib/linux/cpu/utilization/system.sql
src/trace_processor/perfetto_sql/stdlib/linux/cpu/utilization/thread.sql
src/trace_processor/perfetto_sql/stdlib/sched/time_in_state.sql
test/trace_processor/diff_tests/stdlib/linux/cpu.py

This change introduces functions to calculate CPU utilization, accounting for potential suspend periods by using the monotonic clock for computation of durations.
Added 'awake_runtime' column to the result of the functions:
- 'cpu_cycles_in_interval'
- 'cpu_cycles_per_thread_in_interval'
- 'cpu_cycles_per_process_in_interval' This new column measures runtime using 'sum(to_monotonic(ii.ts + ii.dur)- to_monotonic(ii.ts))', ensuring that time elapsed during system suspend is not included in the duration.
Introduced new utilization functions:
1. 'cpu_utilization_in_interval': all CPUs utilization over given interval;
2. 'cpu_thread_utilization_in_interval': per thread_name utilization over given interval;
3. 'cpu_process_utilization_in_interval': per process_name utilization over given …

stdlib: Add suspend-aware CPU utilization metrics

---

src/base/http/http_server_unittest.cc
src/base/metatrace_unittest.cc
src/base/scoped_sched_boost_unittest.cc
src/base/unix_socket_unittest.cc

[Not needed and deprecated][0]. This PR will help unblock rolling GoogleTest in Chromium: https://crbug.com/439838457
`gemini-cli` assisted with the generation of this PR.
[0]: https://github.com/google/googletest/blob/a05c0915074bcd1b82f232e081da9bb6c205c28d/googlemock/include/gmock/gmock-actions.h#L2045

Clean up single-arg `testing::Invoke()`s in `src/base/` (1/n)

---

src/trace_processor/importers/proto/winscope/surfaceflinger_layers_parser.cc
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_utils.h
src/trace_processor/importers/proto/winscope/surfaceflinger_layers_visibility_computation.cc
src/trace_processor/importers/proto/winscope/winscope_geometry.cc
src/trace_processor/importers/proto/winscope/winscope_geometry.h
src/trace_processor/importers/proto/winscope/winscope_geometry_unittest.cc
test/trace_processor/diff_tests/parser/android/tests_surfaceflinger_layers.py

Properly account for corner radius in occlusion calculation.
Bug: 312910010
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=WinscopeGeometryRect*
Test: tools/diff_test_trace_processor.py out/linux_clang_release/trace_processor_shell --name-filter="SurfaceFlingerLayer|PerfettoTable:winscope"

tp: Winscope geometry fixes surfaced from WM flicker tests.

---

OWNERS

Grant Ashwin and Kirill android owners. Mainly to approve github->android-internal merges at this point.
I've also removed the chromium accounts because the related workflows now work against github (our new source of truth). Keeping the chrometto @google account for now, but can remove those as well.

android: update OWNERS

---

ui/src/plugins/dev.perfetto.ExplorePage/explore_page.ts
ui/src/plugins/dev.perfetto.ExplorePage/json_handler.ts
ui/src/plugins/dev.perfetto.ExplorePage/json_handler_unittest.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.scss
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/graph.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_box.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/modify_columns_node.scss
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/modify_columns_node.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts
ui/src/plugins/dev.perfetto.SqlModules/sql_modules.ts

This commit introduces a new "Modify Columns" node to the Explore Page query builder.
* New Functionality: Users can now add a "Modify Columns" node to their query graph. This node allows them to:
* Select, reorder, and rename columns from the previous node.
* Add new columns defined by SQL expressions.
* Filter the results based on the final set of columns.
* UI Changes: A "Modify Columns" option has been added to the menu when adding a new node in the query builder UI.
* Serialization: The new node's state (which columns are selected, new column definitions, filters, etc.) can be saved and loaded, so queries using this feature can be shared and restored.
* Testing: Unit tests have been added to ensure the serialization and deserialization of the new node work correctly.

exp: Modify Columns node

---

ui/src/plugins/dev.perfetto.ExplorePage/query_builder/builder.scss
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/node_box.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/aggregation_node.scss
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/aggregation_node.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_builder/nodes/sources/slices_source.ts
ui/src/plugins/dev.perfetto.ExplorePage/query_node.ts

The commit introduces a feature that displays configuration details directly on the nodes. Specifically, it adds a summary of the settings for "Aggregation" and "Slices Source" nodes. For example, an Aggregation node will now show which columns it's grouping by and what aggregate functions are being used.

exp: Show details on nodes

---

src/trace_processor/util/regex.h

MSVC does not see that out is used in the non-Windows branch.

tp: fix: fix regex.h build on windows

---

ui/src/plugins/org.kernel.Wattson/index.ts
ui/src/plugins/org.kernel.Wattson/styles.scss

In case users missed some necessary ftrace_events for Wattson, Perfetto UI will show nothing which confuses the users. There needs to be warning messages telling user which bare minimum ftrace_events he forgot adding in Perfetto Trace Config. It's per track and not for the whole Wattson group because the missing traces might be different per track.
For short-term, this patchset is reusing the "help" icon to display the warning messages. The missing events will be generated by comparing between bare minimum trace events and user's configured events. Once generated, missing events will be passed to each CPU Estimate Track and display in red color: "Perfetto trace configuration is missing below events for Wattson to work :<missing_event_list>"  Limitation is that user needs to hover over the …

ui: Add warning messages for missing trace events for each CPU track in Wattson

---

src/trace_processor/metrics/sql/android/android_jank_cuj.sql
src/trace_processor/metrics/sql/android/jank/internal/counters.sql
src/trace_processor/perfetto_sql/stdlib/android/cujs/sysui_cujs.sql
src/trace_processor/perfetto_sql/stdlib/android/frames/timeline.sql
test/trace_processor/diff_tests/metrics/graphics/android_jank_cuj.out
test/trace_processor/diff_tests/metrics/graphics/android_jank_cuj_query_test.sql
test/trace_processor/diff_tests/stdlib/android/sysui_cujs_test.py

This reverts commit 4c804d94ed6dd737ba0ef3d190811fa79bebf5a2.
Failing roll into Google3: http://fusion2/presubmit/807538954/OCL:807538954:BASE:807642419:1758022636326:b51f8c80/targets/invocations/bcead98a-2fd7-43df-b1f3-63ab0bad8da1/targets/%2F%2Fjavatests%2Fcom%2Fgoogle%2Fwireless%2Fandroid%2Ftelemetry%2Fpipelines%2Ftraceextractor%2Fpower:MediumTests/tests

Revert "Migrate android_jank_cuj metric to use stdlib tables and local composition. (#2182)"

---

src/trace_processor/trace_summary/summary.cc

We're getting integer precision loss cast issues

tp: fix compile on Windows

---

tools/release_sdk.py

Necessary because the amalgamated sources should intentionally not be covered by presubmit checks

tools: push release branch with --no-verify

---

src/trace_processor/perfetto_sql/stdlib/android/kernel_wakelocks.sql

For a typical long trace this goes from 9.4s to 1.6s.
Bug: http://b/445123061

Speed up android.kernel_wakelocks using counter_leading_intervals().

---

ui/src/frontend/sidebar.ts

Currently when you click the current trace name in the sidebar, it copies the trace's URL to the clipboard. This rarely makes sense anymore and this functionality has been superseded by the share dialog.

ui: Remove click handler from current trace name in sidebar

---

src/trace_processor/importers/android_bugreport/android_log_event.cc
src/trace_processor/importers/android_bugreport/android_log_reader.cc
src/trace_processor/importers/android_bugreport/android_log_reader.h
src/trace_processor/importers/android_bugreport/android_log_unittest.cc

Currently Perfetto can only parse dates of the format MM-DD, however
this requires Perfetto to guess the year, however this is error prone
and can fail in a number of ways:
- for dates like 01-01 it is unclear if it is Jan 1st of the current
year or Jan 1st 1970 which sometimes shows up in logcat when incorrect
clock is used or system clock is not set at boot.
- for traces that span the new year boundary guessing a single year
for all log events is not sufficient.
Allow users to provide the year via commands like `adb logcat -v year`
in order to bypass Perfetto's year guessing logic so they don't get
tripped up by corner cases. Year guessing will still remain in place when
the year is not provided in the logs.

tp: support YYYY-MM-DD logcat date format

---

ui/src/core/app_impl.ts
ui/src/core_plugins/dev.perfetto.CoreCommands/index.ts
ui/src/frontend/is_internal_user_script_loader.ts

Allows for hypothetical multiple sets of macros to be injected. We have
one today but this aligns better with the future intention of this API.

ui: make extra macros an array

---

infra/ci/worker/sandbox_runner.py
tools/extract_linux_syscall_tables
tools/gen_amalgamated_python_tools
tools/roll-prebuilts

Perfetto's scripts use `os.rename` to replace files with new versions. However, `os.rename` fails on Windows when the destination file exists.
`os.replace` is equivalent to `os.rename` on POSIX, and on Windows allows replacing an existing file (see [docs](https://docs.python.org/3/library/os.html#os.rename)). This change replaces uses of `os.rename` with `os.replace`, because the scripts don't seem like they intend to fail if the file already exists.
This fixes the following error on Windows:
```
PS C:\src\perfetto> python3 tools/gen_all out/default
Running python3 tools\check_include_violations
Running python3 tools\check_proto_comments
Running python3 tools\fix_include_guards
0 files changed
Running python3 tools\gen_merged_protos
Running python3 tools\gen_amalgamated_python_tools
INFO …
```

Use os.replace instead of os.rename

---

Android.bp
BUILD
src/trace_processor/importers/proto/winscope/BUILD.gn
src/trace_processor/importers/proto/winscope/viewcapture_test_utils.h
src/trace_processor/importers/proto/winscope/viewcapture_views_extractor.cc
src/trace_processor/importers/proto/winscope/viewcapture_views_extractor.h
src/trace_processor/importers/proto/winscope/viewcapture_views_extractor_unittest.cc

To process views in DFS order for visibility computation.
Bug: 438683146
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=ViewCapture*

tp: Introduce view capture extractor.

---

ui/src/components/tracks/base_slice_track.ts

Currently we make the assumption in BaseSliceTrack that slices are ordered by `ts`, which allows us to perform a very specific optimization which avoids rendering anything when the first slice is off the right hand side of the viewport.
However, slices from the mipmap function are ordered by depth first then ts, meaning that slices are not necessarily sorted by ts. In practice, slices at lower depths usually do start before those at higher depths anyway, so this is usually not an issue.
This patch removes the optimization entirely as it seems pretty dubious whether it actually helps all that much.
Fixes: https://buganizer.corp.google.com/issues/446503267

ui: Fix disappearing slices by removing an optimization that assumes sorted slices in BaseSliceTrack

---

src/trace_processor/importers/proto/gpu_event_parser.cc
src/trace_processor/importers/proto/gpu_event_parser.h
src/trace_processor/importers/proto/graphics_event_module.cc
src/trace_processor/importers/proto/graphics_event_module.h

Turns out some GPU vendors set timestamps on descriptor packets which are broken and are ending up less than zero (because of different clock + clock sync).
Fix this by handling gpu descriptors at tokenization time instead. This ensures they are always handled first.
Fixes: https://github.com/google/perfetto/issues/3055

tp: fix parsing of gpu counter descriptors

---

src/trace_processor/dataframe/dataframe.cc
src/trace_processor/dataframe/dataframe.h
src/trace_processor/dataframe/impl/query_plan.cc
src/trace_processor/dataframe/impl/query_plan.h

Lots of places include dataframe.h and query_plan.h which also
indirectly caused including the whole bytecode. But this was only used
for string conversion which barely *any* code needs to care about.
Out-line those to speed up TP builds signifcantly.

tp: significantly speed up compile time of tp

---

ui/src/components/tracks/debug_slice_track_details_panel.ts
ui/src/plugins/org.chromium.ChromeCriticalUserInteractions/generic_slice_details_tab.ts
ui/src/plugins/org.chromium.ChromeCriticalUserInteractions/startup_details_panel.ts
ui/src/plugins/org.chromium.ChromeCriticalUserInteractions/web_content_interaction_details_panel.ts
ui/src/plugins/org.chromium.ChromeScrollJank/scroll_details_panel.ts
ui/src/plugins/org.chromium.ChromeScrollJank/scroll_jank_v3_details_panel.ts
ui/src/widgets/tree.ts

This patch is a small code tidy up. It should contain zero functional changes.
Currently we use two utility functions `dictToTreeNodes()` and `dictToTree()` to  generate `m(Tree, ...)` and `m(TreeNode, ...)` widgets from dicts. While on paper these seem reasonable, they actually add a layer of indirection to the code which makes it confusing to write, read, and modify. Using `m(TreeNode, ...)` directly really isn't that much of a hardship, and permits usage of familiar mithril niceties such as conditional rendering. I.e. `conditional && m(TreeNode, {...})`

ui: Remove dictToTreeNodes() and friends, use TreeNode directly

---

ui/src/assets/widgets/card.scss

Card widgets with 'interactive: true' configured are essentially inviting the user to click on them. Set the cursor to pointer as an extra hint that they are clickable.

ui: Set `cursor: pointer` on interactive cards

---

docs/getting-started/converting.md

Those links were broken. I guess this are the correct ones now.

Fix links on documentation

---

src/trace_processor/importers/proto/winscope/protolog_message_decoder.cc
src/trace_processor/storage/stats.h

The ProtoLogMessageDecoder would crash with a segmentation fault when processing a message where the number of format specifiers did not match the number of provided parameters. This was caused by reading past the end of the parameter vectors.
This change adds defensive checks to validate that a parameter exists before it is accessed. If a parameter is missing, a placeholder string "[MISSING_PARAM]" is used instead, and a stat is incremented to track the occurrence of these mismatches.
This is a defensive fix, as the writer-side code should ideally prevent these mismatches from being written into the trace.
Bug: 447556988
Test: Manually verified with the trace from the bug.

Fix crash in ProtoLogMessageDecoder on param mismatch

---

src/trace_processor/importers/proto/winscope/test/windowmanager_hierarchy_walker_unittest.cc
src/trace_processor/importers/proto/winscope/test/windowmanager_sample_protos.h
src/trace_processor/importers/proto/winscope/windowmanager_hierarchy_walker.cc
src/trace_processor/importers/proto/winscope/windowmanager_hierarchy_walker.h
src/trace_processor/importers/proto/winscope/windowmanager_parser.cc
src/trace_processor/perfetto_sql/stdlib/android/winscope/windowmanager.sql
src/trace_processor/tables/winscope_tables.py

Required to build hierarchy.
Bug: 438681230
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=WindowManager*
Test: tools/diff_test_trace_processor.py out/linux_clang_debug/trace_processor_shell --name-filter="PerfettoTable:winscope|WindowManager"

tp: Extend WM tables with name overrides.

---

src/protozero/filtering/filter_util.cc
src/trace_processor/trace_processor_shell.cc

The new RecordError and RecordWarning methods were added in version 4.22.0 of the C++ library and the old AddError and AddWarning methods were removed in version 5.26.0.
This was partially addressed in https://github.com/google/perfetto/pull/3082
Should fix issue #992

Update protozero error reporter for Protobuf 26.x.

---

src/trace_processor/importers/proto/winscope/windowmanager_parser.cc
src/trace_processor/perfetto_sql/stdlib/android/winscope/windowmanager.sql
src/trace_processor/tables/winscope_tables.py
test/trace_processor/diff_tests/parser/android/tests_windowmanager.py
test/trace_processor/diff_tests/parser/android/windowmanager.textproto

Required for active display selection.
Bug: 438681230
Test: tools/ninja -C out/linux_clang_debug perfetto_unittests && out/linux_clang_debug/perfetto_unittests --gtest_filter=WindowManager*
Test: tools/diff_test_trace_processor.py out/linux_clang_debug/trace_processor_shell --name-filter="PerfettoTable:winscope|WindowManager"

tp: Extend WM tables with focused display id.

---

ui/src/core/load_trace.ts

The UI currently always switches to the timeline page after loading a trace, which makes it impossible to share a link to a specific page. Now that more and more pages are being added to the UI, some pages are going to be equally as important as the timeline page, so it no longer makes sense to switch to hard switch to the timeline page.
This patch makes it so that we attempt to preseve the current page, only switching to the timeline page if we are currently on the home page.

ui: Retain page when loading a trace

---

src/trace_processor/importers/etw/etw_parser.cc

The ETW parser for CSwitch events was attempting to read an incorrect field to determine the thread wait reason. The etw.proto defines this as a oneof field, old_thread_wait_reason_enum_or_int.
This change updates the parser to correctly handle this oneof. It now prioritizes the integer representation (old_thread_wait_reason_int) for broader compatibility and defaults to 0 if the field is not present, ensuring robust parsing of the wait reason.

Fix ETW CSwitch wait reason parsing

---

ui/src/widgets/popper_utils.ts
ui/src/widgets/popup.ts

Since popups are rendered out-of-tree, if a trigger becomes invisible due to it or one of its parents having display:none set, then the popup itself doesn't automatically become invisible.
This causes issues when e.g. changing page. Since the previous page is kept in the DOM just with `display:none`, a trigger element with an open popup on that page is not actually removed, just made invisible. However the popup still persists and is left floating awkwardly anchored to (0, 0).
This patch adds a popper.js modifier which detects if the trigger element is visible or not with `element.checkVisibility()`, applying `display:none` to the popup as well.

ui: Hide a popup when its trigger is no longer visible

---

ui/src/components/details/args.ts
ui/src/components/details/slice_args.ts
ui/src/components/sql_utils/args.ts
ui/src/components/sql_utils/slice.ts
ui/src/components/tracks/debug_slice_track_details_panel.ts
ui/src/components/widgets/sql/details/details.ts
ui/src/plugins/dev.perfetto.Ftrace/ftrace_details_panel.ts
ui/src/plugins/dev.perfetto.Screenshots/screenshot_panel.ts
ui/src/plugins/dev.perfetto.TraceProcessorTrack/counter_details_panel.ts

Leverage the new print_args() function to avoid reconstructing the args tree in JS.
This change doesn't affect UX, just simplifies the code.

ui: refactor display of args

---

docs/analysis/trace-summary.md
protos/perfetto/perfetto_sql/structured_query.proto
src/trace_processor/perfetto_sql/generator/structured_query_generator.cc
src/trace_processor/perfetto_sql/generator/structured_query_generator_unittest.cc

When no column_name was specified in the aggregation we would just silently treat column_name as an empty string. It made COUNT() work by mistake.
Now it's explicit, with tests, and proper difinition of optional/required fields with checks in code.

tp: Add COUNT(*) aggregation to StructuredQuery

---

src/perfetto_cmd/config.cc
src/perfetto_cmd/perfetto_cmd.cc
src/profiling/deobfuscator.cc
src/profiling/symbolizer/local_symbolizer.cc
src/profiling/symbolizer/local_symbolizer.h
src/protozero/text_to_proto/text_to_proto.cc
src/trace_processor/importers/instruments/instruments_xml_tokenizer.cc
src/trace_processor/importers/perf/features.cc
src/trace_processor/importers/proto/pigweed_detokenizer.cc
src/trace_processor/perfetto_sql/intrinsics/functions/pprof_functions.cc
src/trace_processor/perfetto_sql/intrinsics/functions/replace_numbers_function.cc
src/trace_processor/perfetto_sql/intrinsics/functions/replace_numbers_function.h
src/trace_processor/trace_processor_shell.cc
src/traceconv/pprof_builder.cc
src/traceconv/trace_to_profile.cc
src/traceconv/trace_to_profile.h
src/traced/probes/sys_stats/sys_stats_data_source.cc
src/tracing/service/tracing_service_impl.cc

This PR fixes many of the performance issues reported by cppcheck.
I have one question:
cppcheck mentions that using std::move() when returning by value prevents some compiler optimizations (copy elision).
Yet, the warning gets specifically mentioned as a code comment in
https://github.com/google/perfetto/blob/main/src/profiling/common/producer_support.cc#L48
Is there a reason for using `std::move` there?
To be fair, I saw `std::move` a couple times throughout the code I was fixing. I fixed some of the instances in this PR.

More cppcheck performance fixes

---

tools/install-build-deps

Turns out we were trying to use the arm64 binary on x64 which obviously
would not work as there's no "reverse Rosetta". Use the x64 version
where appropriate.
Fixes: https://github.com/google/perfetto/issues/3166

buildtools: add x64 emscripten for macos

---

src/trace_processor/trace_processor_storage_impl.cc

Bug has been found with new extra parsing descriptor feature. This PR is to rollback what is breaking normal trace viewing.

temporarily disable custom descriptor loading due to bug

---

ui/src/frontend/sidebar.ts

This is a workaround for a mithril bug.
The bug is somewhere in the logic that recycles DOM nodes and applies the differences.
If you flip back and forth between null and '_blank' eventually
mithril will get in a weird state and promote null to 'null'.
The minified repro is the following:
cnt++;
const repro =[
m('a', {href: '#', target: null}, 'one'),
m('a', {href: '#', target: (cnt % 2 == 0) ? null : '_blank'}, 'two'),
m('a', {href: '#', target: null}, 'three'),
];
After 2 render passes the second entry becomes target="null"
Bug: b/449784590

ui: fix sidebar accidentally opening links on a new window

---

ui/src/frontend/sidebar.ts

This was removed in https://github.com/google/perfetto/pull/2979

ui: remove tooltip for trace name for copying

---

include/perfetto/ext/tracing/core/consumer.h
include/perfetto/ext/tracing/core/tracing_service.h
protos/perfetto/ipc/consumer_port.proto
src/perfetto_cmd/perfetto_cmd.cc
src/perfetto_cmd/perfetto_cmd.h
src/tracing/internal/tracing_muxer_impl.cc
src/tracing/ipc/consumer/consumer_ipc_client_impl.cc
src/tracing/ipc/service/consumer_ipc_service.cc
src/tracing/service/tracing_service_impl.cc
src/tracing/service/tracing_service_impl.h
src/tracing/service/tracing_service_impl_unittest.cc
src/tracing/test/mock_consumer.cc
test/cmdline_integrationtest.cc

This reverts commit b5a3a4b38331ca4b3362a664451799b437fcc5f5.
Needs accompanying selinux changes (traced to be able to receive additional fds from perfetto_cmd) to roll into Android. Reverting to unblock the roll until that patch is ready & reviewed.

Revert "Support clone operation for 'write_into_file' sessions. (#2871)"

---

src/trace_processor/importers/proto/android_probes_module.cc
src/trace_processor/importers/proto/android_probes_module.h
src/trace_processor/importers/proto/android_probes_parser.cc
src/trace_processor/importers/proto/android_probes_parser.h
test/trace_processor/diff_tests/parser/parsing/tests.py

Refactor the android_probes parser to correctly handle out-of-order events by pushing the data through TraceSorter. 
Instead of parsing power_rails and android_log packets immediately, the module now breaks them into individual events, wraps each one in a new TracePacket, and pushes them to the sorter's queue.

tp: android_probes_parser pushes events into TraceSorter
